### ISSUE TITLE
ImVector deprecation if not needed

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#103]
As a result of binding ImVector some problems resulted in imgui 1.73
https://github.com/ocornut/imgui/issues/2801

If nobody ask for them they will be dropped

**Comment by lmariscal** [comment]
I don find them useful when working with custom widgets, but I can see them easily replaced by any integrated Vector type of the target language.

What I would like to know is, if they are deprecated what will their successor be? As their data type is:

```cpp
    int                 Size;
    int                 Capacity;
    T*                  Data;
```

**Comment by ocornut** [comment]
Please note that if somehow favorable to your users, you could just mask out some functions such as `find()` and leave working functions in.

**Comment by sonoro1234** [comment]
> if they are deprecated what will their successor be?

```c 
typedef struct ImVector{int Size;int Capacity;void* Data;} ImVector;
```

**Comment by sonoro1234** [comment]
> Please note that if somehow favorable to your users, you could just mask out some functions such as `find()` and leave working functions in.

Lets see is someone else appears in the conversation asking for that
@mellinoe  @Gekkio  ...

**Comment by Gekkio** [comment]
I think imgui-rs is ok with just the `void*` version, so I vote for dropping the problematic `ImVector` types. :smiley:

**Comment by mellinoe** [comment]
`ImVector` is already handled in a completely custom way in ImGui.NET, so I'm not too concerned about things being removed from the parsed definitions list. ImVector is a unique enough type that it is just easier to make it C#-friendly by hand than to auto-generate something.

**Comment by sonoro1234** [comment]
Finally all ImVector template functions are dropped now

**Comment by sonoro1234** [comment]
question was answered and decision maked!!
