### ISSUE TITLE
Periodically testing latest imgui

### ISSUE THREAD

**Issue by rokups** [cimgui/cimgui#106]
Hey,
It would be great if cimgui periodically tested builds with latest imgui in order to spot possible breakages early. As far as i know there is no way to do scheduled builds with travis (correct me if im wrong). It is possible with github actions though. I could write needed scripts to do that. Would there be any interest in using github actions for this? I could implement normal CI builds as well if you prefer (and drop travis). Let me know what your thoughts are.

**Comment by sonoro1234** [comment]
Perhaps in a testing branch? (Not master)

**Comment by rokups** [comment]
Sure whatever works for you. Ill cook it up in coming days :+1:

**Comment by lmariscal** [comment]
If it works for something here is the CI in github actions: https://github.com/nimgl/cimgui/blob/master/.github/workflows/cpp.yml

**Comment by rokups** [comment]
This definitely helps. Adding scheduled builds using master branch will be very easy now. Thanks for saving me hour of work :)

**Comment by rokups** [comment]
Here it is: https://github.com/rokups/cimgui/tree/workflows

Before pulling in this branch you would need to sign your account up for github actions beta: https://github.com/features/actions

On push/pull request it runs normal build with imgui checked out from submodule.

On every monday it will try to build imgui with version checked out from ocornut/imgui master branch. At the moment that fails with:
> cimgui_test: /tmp/cimgui/imgui/imgui.cpp:3075: bool ImGui::DebugCheckVersionAndDataLayout(const char*, size_t, size_t, size_t, size_t, size_t, size_t): Assertion `sz_io == sizeof(ImGuiIO) && "Mismatched struct layout!"' failed.
[1]    6787 abort (core dumped)  ./cimgui_test

Build looks like so: https://github.com/rokups/cimgui/commit/59583ea35a2eb7019223477bc1fa891fd57b1b86/checks?check_suite_id=296051479

**Comment by sonoro1234** [comment]
> On every monday it will try to build imgui with version checked out from ocornut/imgui master branch. At the moment that fails with:
> 
> > cimgui_test: /tmp/cimgui/imgui/imgui.cpp:3075: bool ImGui::DebugCheckVersionAndDataLayout(const char*, size_t, size_t, size_t, size_t, size_t, size_t): Assertion `sz_io == sizeof(ImGuiIO) && "Mismatched struct layout!"' failed.
> > [1]    6787 abort (core dumped)  ./cimgui_test

I dont understand where this fail is shown.

My test was:
1-pull latest imgui
2-regenerate with generator.bat
3-cmake ../cimgui
4-make

There was no fail!!

**Comment by rokups** [comment]
Build script does not regenerate bindings. I will try adding that

**Comment by sonoro1234** [comment]
@lmariscal 
Also: I am not able to compile cimgui_test:
`cmake  ../cimgui/test/` and make says
```
[100%] Linking C executable cimgui_test.exe
C:/i686-7.2.0-release-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/bin/l
d.exe: cannot find -lcimgui
```

**Comment by sonoro1234** [comment]
Yes, regenerate bindings is needed.
But I still dont understand where the fail reported is shown in  https://github.com/rokups/cimgui/commit/59583ea35a2eb7019223477bc1fa891fd57b1b86/checks?check_suite_id=296051479

**Comment by rokups** [comment]
Failure i mentioned was reported on https://github.com/rokups/cimgui/commit/5e668008333bf4c69b70296363ca1ab327b6387d/checks?check_suite_id=296049929

As you can see from those build pages github-actions is definitely worth it's beta label :) But when it works - it works pretty nice https://github.com/ocornut/imgui/actions

**Comment by sonoro1234** [comment]
It seems I dont understand how it works:
I have signed up in https://github.com/features/actions
Then pull from https://github.com/rokups/cimgui (branches master and workflow)
Nothing new appeared in `https://github.com/rokups/cimgui/actions`

**Comment by rokups** [comment]
if you pushed workflow branch into cimgui/cimgui repo you should see builds on https://github.com/cimgui/cimgui/actions

**Comment by sonoro1234** [comment]
If it is merged in cimgui/cimgui (master branch). Will this branch be modified by the github action?

**Comment by rokups** [comment]
Well yes, i added .github/workflows/build.yml so that will appear. But do not merge yet. I will set up generator to run tomorrow.

**Comment by rokups** [comment]
Oh no, not at all. CI worker only downloads cimgui/imgui repos and tries to build them. No changes are pushed to any repo.

**Comment by rokups** [comment]
I am done. [Normal builds using submodule](https://github.com/rokups/cimgui/commit/e3136bb882b3789642d581d557beb021a87310f6/checks?check_suite_id=298020435) and builds that [download latest imgui](https://github.com/rokups/cimgui/commit/de4532ae8aeb6af482ccdf350f9c59b501179fb0/checks?check_suite_id=298016036) succeed.

**Comment by sonoro1234** [comment]
> Oh no, not at all. CI worker only downloads cimgui/imgui repos and tries to build them. No changes are pushed to any repo.

Then PR could be done against master branch

**Comment by sonoro1234** [comment]
Thanks to @rokups and @lmariscal  for the work done!!
