### ISSUE TITLE
Build actions fails on macos and windows

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#109]
@rokups Did you saw the failures?

macos failure could be solved by using LuaJIT2.1 instead of LuaJIT2.05
window failure says `the operation was cancelled` which I dont clearly understand

**Comment by sonoro1234** [comment]
Now working again without having changed anything!!??

**Comment by rokups** [comment]
Sorry, i missed email two weeks ago =x Well now it is working so who knows.

**Comment by sonoro1234** [comment]
Let close it until happens again (or not)
