### ISSUE TITLE
cimgui crash on windows

### ISSUE THREAD

**Issue by Milerius** [cimgui/cimgui#113]
```c
#include <stdio.h>
#include <assert.h>
#include "../cimgui.h"

int main(void)
{
  assert(igDebugCheckVersionAndDataLayout(igGetVersion(), sizeof(ImGuiIO), sizeof(ImGuiStyle),
                                          sizeof(ImVec2), sizeof(ImVec4), sizeof(ImDrawVert),
                                          sizeof(ImDrawIdx)));
  printf("CreateContext() - v%s\n", igGetVersion());
  igCreateContext(NULL);
  ImGuiIO *io = igGetIO();

  unsigned char *text_pixels = NULL;
  int text_w, text_h;
  ImFontAtlas_GetTexDataAsRGBA32(io->Fonts, &text_pixels, &text_w, &text_h, NULL);

  for (int n = 0; n < 20; n++) {
    printf("NewFrame() %d\n", n);

    ImVec2 display_size;
    display_size.x = 1920;
    display_size.y = 1080;
    io->DisplaySize = display_size;
    io->DeltaTime = 1.0f / 60.0f;
    igNewFrame();

    static float f = 0.0f;
    igText("Hello World!");
    igSliderFloat("float", &f, 0.0f, 1.0f, "%.3f", 1.0f);
    igText("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io->Framerate, io->Framerate);
    igShowDemoWindow(NULL);


    ImVec2 dummy;
    dummy.x = 1280.0;
    dummy.y = 720.0;
    igSetNextWindowSize(dummy, ImGuiCond_FirstUseEver);
    static bool is_open = true;
    igBegin("foo", &is_open, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_MenuBar);
    printf("%f", igGetWindowSize().x); //< crash here
    igEnd();

    igRender();
  }

  printf("DestroyContext()\n");
  igDestroyContext(NULL);

  return 0;
}
```

I was crashing on windows on my side, so i decided to investigate, modifying the test to this snippet make the code crash directly (`igGetWindowSize().x`)

Crash here: 
![image](https://user-images.githubusercontent.com/21139416/71319905-a46c0300-24a4-11ea-9dda-e2c2401d4130.png)

![image](https://user-images.githubusercontent.com/21139416/71319918-bbaaf080-24a4-11ea-8096-2acdd47daf03.png)

Discovering it using the nim port  of @lmariscal .

Compiler where i'm able to reproduce the crash:

Msvc: 19.24.28314 for x64
clang: clang-9
clang-cl: clang-9

and It's working with mingw, (not same calling convention !)

The compilation warn you about: `C4190`: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4190?view=vs-2019

And i think it's related to: https://github.com/ocornut/imgui/issues/1879#issuecomment-472219067

Please @PathogenDavid and @lmariscal can you confirm that you are able to reproduce the same crash ?

**Comment by Milerius** [comment]
My personal opinion is that the project violates the Windows calling conventions and tries to transform a dereferenced pointer from a C++ structure to a C structure which have a different layout which is completely illegal.

**Comment by Milerius** [comment]
![image](https://user-images.githubusercontent.com/21139416/71320474-05e3a000-24ac-11ea-98ba-e023a39c5011.png)

I tested to print the sizeof it's the same on windows with MSVC in C / C++ so the problem is elsewhere.

**Comment by Folling** [comment]
As pointed out in the [issue you linked to](https://github.com/ocornut/imgui/issues/1879#issuecomment-472219067)
The calling convention windows uses appears to be the issue here. However that calling convention is only necessary because `ImVec2` is **not** a [pod](https://en.cppreference.com/w/cpp/types/is_pod), and that's solely because it has a constructor.
Without constructors, windows wouldn't do the following:

> On x64 Windows (and seemingly, x86 Windows), a function like this:
```cpp
ImVec2 GetWindowPos(ImGuiViewport* viewport)
{
    printf("GetWindowPos(%d)\n", viewport->ID);
    return ImVec2(1879.f, 3226.f);
}
```
> is effectively rewritten to look like this:
```
ImVec2* GetWindowPos(ImVec2* ret, ImGuiViewport* viewport)
{
    printf("GetWindowPos(%d)\n", viewport->ID);
    *ret = ImVec2(1879.f, 3226.f);
    return ret;
}
```

**Comment by sonoro1234** [comment]
nonUDT versión of function should be used

**Comment by Milerius** [comment]
So we have to allocate memory each time we call an ImGui function that return those kind of user data type ?

I'm surprised

**Comment by sonoro1234** [comment]
nonUDT2 avoids you to make preallocation, but could crash depending on compiler.
Do as in LuaJIT-imgui!!!

**Comment by Milerius** [comment]
Okok thank's for specification

**Comment by lmariscal** [comment]
Just read this, @sonoro1234 would you recommend making helper functions like your nonUDT versions in the bindings or should users be the ones responsible?

**Comment by sonoro1234** [comment]
I would recomend doing as done in LuaJIT-imgui
