### ISSUE TITLE
Failed to build cimgui 

### ISSUE THREAD

**Issue by DanielSchreiberMendes** [cimgui/cimgui#116]
Hey when I download the project and want to build it with make, a compilation error occurs.
$ make
g++ -O2 -fno-exceptions -fno-rtti -I./imgui/ -Wall -shared -fPIC -c -o cimgui.o cimgui.cpp
cimgui.cpp:4:10: fatal error: ./imgui/imgui.h: No such file or directory
 #include "./imgui/imgui.h"

Thanks for any help.

**Comment by Dominaezzz** [comment]
You have to clone recursively. Or download imgui and stick it in the imgui folder.

**Comment by sonoro1234** [comment]
Solved
