### ISSUE TITLE
Failed to include cimgui.

### ISSUE THREAD

**Issue by DanielSchreiberMendes** [cimgui/cimgui#118]
Hello, 
I cloned the cimgui wrapper and imgui and put it into the imgui folder and built cimgui with make. When I tried to link it with -lcimgui and include it said "cimgui/cimgui.h: No such file or directory". I tried to put the cimgui.so file manually into the usr/local/lib folder and the cimgui.h file into the usr/local/include folder but the compiler said e.g "error: unknown type name ‘ImVec2’;" for everything that began with "Im".  
What do I have to do? Thanks for your help :)

**Comment by Dominaezzz** [comment]
You need to define `CIMGUI_DEFINE_ENUMS_AND_STRUCTS` to get the imgui types redefined in the header.

(Don't forget to close the other issue).

**Comment by sonoro1234** [comment]
Build test with: https://github.com/cimgui/cimgui/blob/master/test/CMakeLists.txt
Build library without implementations: https://github.com/cimgui/cimgui/blob/master/CMakeLists.txt
Build library with some implementations: https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/CMakeLists.txt

**Comment by DanielSchreiberMendes** [comment]
Thank you very much
