### ISSUE TITLE
Need help linking / installing.

### ISSUE THREAD

**Issue by ITotalJustice** [cimgui/cimgui#128]
Hi. I am using linux - ubuntu and i have compiled the latest version from source.

For some reason, i am unable to link against cimgui no matter what i try. I installed cimgui to `/usr/local/lib/` however I get the error `/usr/bin/ld: cannot find -lcimgui`. So then i tried manually linking with `gcc -L/usr/local/lib main.c -lcimgui` and i still have the error. The path `/usr/local/lib` is where i have all of my shared libs so I know there's no issue there. Also the test fails to find the lib also.

I am probably missing something really obvious, but I genuinely have no idea what that is :smile:

**Comment by sonoro1234** [comment]
Firs of all:
What are you trying to achieve compiling cimgui?
Are you aware that cimgui is intended for making bindings?

**Comment by ITotalJustice** [comment]
Thanks for replying.

Maybe I am misunderstanding cimgui. My goal is to be able to use imgui functions in C.

**Comment by sonoro1234** [comment]
The test will show you how to link, but you will also need to use an implementation.
C implementations with SDL are found in
https://github.com/haxpor/sdl2-cimgui-demo and https://github.com/canoi12/cimgui_c_sdl2_example/tree/master/include/imgui_impl
for GLFW3 you have https://github.com/peko/cimgui-c-example

I have not tried neither of them

**Comment by ITotalJustice** [comment]
Thank you for the linked examples. https://github.com/haxpor/sdl2-cimgui-demo helped solve my issue. :+1:
