### ISSUE TITLE
Incorrect name and data type for ImDrawListSharedData in structs_and_enums.json

### ISSUE THREAD

**Issue by lmariscal** [cimgui/cimgui#129]
Hi, parsing this data is causing errors on my end.
Is this correct?
https://github.com/cimgui/cimgui/blob/master/generator/output/structs_and_enums.json#L2682

In the header the structure definition is:
```c
struct ImDrawListSharedData
{
    ImVec2 TexUvWhitePixel;
    ImFont* Font;
    float FontSize;
    float CurveTessellationTol;
    float CircleSegmentMaxError;
    ImVec4 ClipRectFullscreen;
    ImDrawListFlags InitialFlags;
    ImVec2 ArcFastVtx[12 * 1];
    ImU8 CircleSegmentCounts[64];
};
```
But on the generated json file it takes ```ArcFastVtx``` as:
```json
{
  "name": "1]",
  "type": "ImVec2 ArcFastVtx[12 *"
},
```

**Comment by lmariscal** [comment]
It seems that a similar error happens in:
https://github.com/cimgui/cimgui/blob/master/generator/output/structs_and_enums.json#L4854

```json
    "ImGuiStyleMod": [
      {
        "name": "VarIdx",
        "type": "ImGuiStyleVar"
      },
      {
        "name": "}",
        "type": "union { int BackupInt[2]; float BackupFloat[2];"
      }
    ],
```

**Comment by sonoro1234** [comment]
Thanks for reporting.
Should be corrected now.
TODO: instead of add exceptional corrections for unnamed unions parse them correctly.
