### ISSUE TITLE
Need helps on adding implementations

### ISSUE THREAD

**Issue by Xiderowg** [cimgui/cimgui#131]
Hi, I want to add win32, dx9 and dx11 implementations to cimgui, so I modify generator.bat line 19 from
`luajit ./generator.lua gcc glfw opengl3 opengl2 sdl`
to 
`luajit ./generator.lua gcc glfw opengl3 opengl2 sdl win32 dx9 dx11`
and configure PATH for luajit and mingw successfully.

After running generator.bat, everything goes well with 0 error, 3 warning
`------------------implementations generation with gcc------------------------
../imgui/examples/imgui_impl_win32.h:10:9: warning: #pragma once in main file
 #pragma once
         ^~~~
../imgui/examples/imgui_impl_dx9.h:12:9: warning: #pragma once in main file
 #pragma once
         ^~~~
../imgui/examples/imgui_impl_dx11.h:12:9: warning: #pragma once in main file
 #pragma once`
but after compiling with mingw, my C# program can't find any entry like ImGui_ImplWin32_*** /ImGui_ImplDX9_*** /ImGui_ImplDX11_***.
what am I doing wrong here, any help will be highly appreciated, thanks in advance.

**Comment by Xiderowg** [comment]
the output of generator.bat
`gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


HAVE_COMPILER   true
INTERNAL_GENERATION     true
IMGUI_VERSION   "1.76"
------------------generation with gcc------------------------
reference to no const arg in    swap    (ImVector& rhs) ImVector& rhs
reference to no const arg in    ImTriangleBarycentricCoords     (const ImVec2& a,const ImVec2& b,const ImVec2& c,const ImVec2& p,float& out_u,float& out_v,float& out_w)        float& out_u
reference to no const arg in    ImTriangleBarycentricCoords     (const ImVec2& a,const ImVec2& b,const ImVec2& c,const ImVec2& p,float& out_u,float& out_v,float& out_w)        float& out_v
reference to no const arg in    ImTriangleBarycentricCoords     (const ImVec2& a,const ImVec2& b,const ImVec2& c,const ImVec2& p,float& out_u,float& out_v,float& out_w)        float& out_w
-----------------check arg detection---------------------------
-----------------end check arg detection-----------------------
-----------------check arg detection---------------------------
-----------------end check arg detection-----------------------
{
        ["ImVector"]={
                ["float"]="float"
                ["ImWchar"]="ImWchar"
                ["ImDrawVert"]="ImDrawVert"
                ["ImGuiSettingsHandler"]="ImGuiSettingsHandler"
                ["ImVec4"]="ImVec4"
                ["ImGuiGroupData"]="ImGuiGroupData"
                ["ImGuiID"]="ImGuiID"
                ["ImGuiWindow*"]="ImGuiWindowPtr"
                ["ImGuiColumnData"]="ImGuiColumnData"
                ["ImGuiColumns"]="ImGuiColumns"
                ["ImVec2"]="ImVec2"
                ["ImFontGlyph"]="ImFontGlyph"
                ["ImGuiTextRange"]="ImGuiTextRange"
                ["ImGuiStoragePair"]="ImGuiStoragePair"
                ["ImGuiStyleMod"]="ImGuiStyleMod"
                ["ImDrawChannel"]="ImDrawChannel"
                ["ImDrawList*"]="ImDrawListPtr"
                ["ImU32"]="ImU32"
                ["ImGuiItemFlags"]="ImGuiItemFlags"
                ["ImFontAtlasCustomRect"]="ImFontAtlasCustomRect"
                ["ImGuiTabItem"]="ImGuiTabItem"
                ["ImGuiShrinkWidthItem"]="ImGuiShrinkWidthItem"
                ["unsigned char"]="unsigned_char"
                ["ImTextureID"]="ImTextureID"
                ["ImFont*"]="ImFontPtr"
                ["ImFontConfig"]="ImFontConfig"
                ["ImGuiColorMod"]="ImGuiColorMod"
                ["ImDrawCmd"]="ImDrawCmd"
                ["ImGuiPtrOrIndex"]="ImGuiPtrOrIndex"
                ["ImGuiPopupData"]="ImGuiPopupData"
                ["ImDrawIdx"]="ImDrawIdx"
                ["char"]="char"}
        ["ImChunkStream"]={
                ["ImGuiWindowSettings"]="ImGuiWindowSettings"}
        ["ImPool"]={
                ["ImGuiTabBar"]="ImGuiTabBar"}}


{
        ["ImVector"]="T"
        ["ImChunkStream"]="T"
        ["ImPool"]="T"}


------------------implementations generation with gcc------------------------
../imgui/examples/imgui_impl_win32.h:10:9: warning: #pragma once in main file
 #pragma once
         ^~~~
../imgui/examples/imgui_impl_dx9.h:12:9: warning: #pragma once in main file
 #pragma once
         ^~~~
../imgui/examples/imgui_impl_dx11.h:12:9: warning: #pragma once in main file
 #pragma once
         ^~~~
-----------------check arg detection---------------------------
-----------------end check arg detection-----------------------
-----------------check arg detection---------------------------
-----------------end check arg detection-----------------------
copyfile        ./output/cimgui.h       ../cimgui.h
copyfile        ./output/cimgui.cpp     ../cimgui.cpp
all done!!`

and the output of mingw make
`process_begin: CreateProcess(NULL, uname -s, ...) failed.
make: Makefile:13: pipe: No error
g++ -O2 -fno-exceptions -fno-rtti -I./imgui/ -Wall -shared -c -o cimgui.o cimgui.cpp
g++ -o cimgui.dll cimgui.o ./imgui/imgui.o ./imgui/imgui_draw.o ./imgui/imgui_demo.o ./imgui/imgui_widgets.o -O2 -fno-exceptions -fno-rtti -I./imgui/ -Wall -shared -limm32
Build complete for "Windows"`

**Comment by sonoro1234** [comment]
It seems that generation was correct and you should have `cimgui/generator/output/cimgui_impl.h` with the C header for the implementations choosed. (Which is not really needed in the building but can help in developing languaje bindings)

You have building issues which I dont understand because I dont know what are you trying to build.

In order to find examples of how to build with implementations you should look in the links provided in README.md as LuaJIT-ImGui (which is my work) or even C examples.

**Comment by Xiderowg** [comment]
Hi sonoro, thank you for your reply. I am recently learning Imgui.NET, and I want to add DirectX 9 and DirectX 11 support to that library, then I find that its compiled version of cimgui.dll doesn't export ImGui_ImplDX*_*** function, so I want to compile it and I meet this problem, what's worse, I know nothing about Lua and little about c++. I discover that cimgui_impl.h has function's declaration that I want but I can't find cimgui_impl.cpp and that header file is not included in cimgui.h. From my own perspective, it is should be automatically generated and included, or should I do that manually? sorry for my ignorance.

**Comment by Xiderowg** [comment]
thank you, problems solved xD
