### ISSUE TITLE
help my ego

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#132]
7410 clones and 1020 Unique cloners in the last 14 days only 502 stars?
;-(

update:
    10,899 Clones
    2,433 Unique cloners

I don't force anyone to clone ;-)

But I shouldn't worry when LuaJIT (such a great piece of code and with so many users) has only 2000 stars...

**Comment by jmgbsas** [comment]
I clone but  do not run, for that reason there is not stars...
imgui.cpp:5:10: fatal error: ./imgui/imgui.h: No such file or directory
   5 | #include "./imgui/imgui.h"
     |          ^~~~~~~~~~~~~~~~~
I rename cimgui.h to imgui.h and put into /imgui but now
cimgui.cpp:9:10: fatal error: ./imgui/imgui_internal.h: No such file or directory
    9 | #include "./imgui/imgui_internal.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
Is not generated , is not true ...then...then  I will need to use generator with Lua
to generate the files,...I did use the command git submodule update but do nothing....when I can to get to work erhaps I will give a start ...Thanks

**Comment by sonoro1234** [comment]
> imgui.cpp:5:10: fatal error: ./imgui/imgui.h: No such file or directory

You forgot to clone recursively as told in https://github.com/cimgui/cimgui#compilation
`git clone --recursive https://github.com/cimgui/cimgui.git`
or
`git submodule update --init --recursive`

**Comment by sonoro1234** [comment]
the joke is fun no more, so closing the issue now.

**Comment by jmgbsas** [comment]
it was not joke.. I am new in Git sorry...I forgot recursive.. he.. happy New Year!!
Thanks for your fast answer!

**Comment by sonoro1234** [comment]
> it was not joke..

Well, it was my joke about stars. 
You should have better opened a new issue.


> (nim, freebasic,Go and Rust will be my tools some day )..

You forgot LuaJIT perhaps

**Comment by jmgbsas** [comment]
Yes!, and waiting for Nelua..!native lua..Cheers from Argentina
