### ISSUE TITLE
Few (potentially) missing definitions

### ISSUE THREAD

**Issue by ff-meli** [cimgui/cimgui#134]
When generating from latest master, with imgui_internal generation enabled, the defintion for ImPool seems to be missing from the output structs_and_enums.

This might be because that type is templated, but it still picks up instances of the type such as 
```
{
    "name": "TabBars",
    "template_type": "ImGuiTabBar",
    "type": "ImPool_ImGuiTabBar"
}
```
inside the definition for ImGuiContext.

ImChunkStream (also templated) is similar.  There may be others, those are the only two I've noticed so far.

If their absence is intentional, is there a recommended way to handle those kinds of types?

**Comment by sonoro1234** [comment]
The templated types are ImVector, ImPool and ImChunkStream.
ImVector_XXX can be used as in (Lua code)

```Lua
local p_ranges = ig.lib.ImVector_ImWchar_create() --ig.ImVector_ImWchar()

local GRB = ig.ImFontGlyphRangesBuilder()
GRB:AddText("Hello world")
GRB:AddChar(0x7262);                               -- Add a specific character
--GRB:AddRanges(ig.GetIO().Fonts:GetGlyphRangesJapanese()); -- Add one of the default ranges
GRB:BuildRanges(p_ranges)
print(p_ranges,p_ranges[0],p_ranges[0].Size,p_ranges[0].Capacity)
local Data = p_ranges[0].Data --ffi.cast("ImWchar*",p_ranges[0].Data)
for i=0,p_ranges[0].Size-1 do
	print(Data[i])
end
ig.lib.ImVector_ImWchar_destroy(p_ranges)
```

Where `ImVector_ImWchar_create()` was manually generated because it was necessary to genetate `ImVector_ImWchar`. Apart from creation (which can only be done with _ImWchar type) the other operations can be done with all ImVector_XXX types (indexing Data and retrieving Size)

In the case of ImPool I dont have use cases so I did not manually created anything for it (Do you have any special need for ImPool?). You can of course use `Buf` or `Map` as another case of ImVector_XXX

**Comment by ff-meli** [comment]
Ah, thank you for that info and the examples.  My repo there is a bit out of date, but the use case of trying to get things working through ImGui.NET via cimgui is still ultimately what I am doing.

I don't have a use for ImPool etc directly, but they currently break ImGui.NET generation because it picks up the instance members in other structs (like TabBars in ImGuiContext) but doesn't have the information to actually generate the type itself.  I figured it would be some amount of manual creation, but I wasn't sure of the correct way to address discrepancies where structs_and_enums contains types that are not present in definitions.

I should be able to get something manual going, that is at least enough to get the built-in types in imgui_internal to work.  Thanks!

**Comment by sonoro1234** [comment]
> doesn't have the information to actually generate the type itself

It can be found in cimgui.h for  ImVector, ImPool and ImChunkStream
```cpp
typedef struct ImPool_ImGuiTabBar {ImVector_ImGuiTabBar Buf;ImGuiStorage Map;ImPoolIdx FreeIdx;} ImPool_ImGuiTabBar;
```
