### ISSUE TITLE
How can backends be used

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#135]
I have just added backend_test folder. You only need to provide to cmake `SDL_PATH` with the path where SDL2 cmake install is done (or leave it empty `-DSDL_PATH=""` if it is in a folder already watched from cmake)
It will generate `cimgui_sdl` module and `test_sdl` executable that will use it from C.
If you are making a binding to another language, you only need to remake what main.c is doing.

This is a description of what is done in https://github.com/sonoro1234/LuaJIT-ImGui to use backends:

C definitions are in: https://github.com/cimgui/cimgui/blob/master/generator/output/cimgui_impl.h
(only sdl, glfw, opengl2 and opengl3 where generated but it is customizable in cimgui generation, see generator.bat (.sh))
There is no C implementation because it suffices to compile any imgui_impl_XXX.cpp for that.
(look at: https://github.com/ocornut/imgui/tree/master/backends and https://github.com/ocornut/imgui/blob/master/docs/BACKENDS.md)

You can then use directly these C definitions or wrap them in you binding languaje as done in https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/lua/imgui/glfw.lua#L183 for example. You will need one platform backend and one renderer backend.
Then use them as done in: https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/lua/imgui/window.lua

**Comment by Sewer56** [comment]
For building on MSVC in conjugation with Visual Studio, you'll need to ensure that preprocessor directives are not wrapped in quotes as the preprocessor will treat the quotes verbatim (will not ignore them).

To do this you'll need to edit your CMake config.
Here's a workaround/fix for MSVC in my own branch of cimgui.

https://github.com/Sewer56/cimgui/commit/06f05bf69349c0758db7d246f3d3139ddc78edcf

**Comment by sonoro1234** [comment]
Thanks for information.
It seems that `\t`  are necessary 
without them:
```
WARNING: Function-style preprocessor definitions may not be passed on the compiler command line because many compilers do not support it.
CMake is dropping a preprocessor definition: __declspec(dllexport)
```
but i could not find information about `\t` (do you have a link to that information?)
I also found strange `\"` when there are not quotes around

**Comment by Sewer56** [comment]
\t is just a tab in Regular Expressions. 
I originally just escaped whitespace by using the backslash `\ `, but I figured that adding a tab instead would make it more readable.

While CMake doesn't support some actual regex in the arguments, it does seem like it supports a small subset of special characters like tab and newline.

**Comment by rootCBR** [comment]
I've been trying to figure this out for hours now. What exactly do I have to do if I wanted to use an Imgui extension like Imnodes using C#? Right now I have the generated output files of cimgui which I specified to use the Imnodes extension - what's left to do for me to start using it in my C# project?

**Comment by sonoro1234** [comment]
This is about using imgui implementations  https://github.com/ocornut/imgui/tree/master/examples not about imgui extensions

> I have the generated output files of cimgui which I specified to use the Imnodes extension

How exactly did you did that?



> what's left to do for me to start using it in my C# project?

cimgui is not a C# project at all. It is a C project from which you can make bindings for other languages (as C#, Lua, etc)

**Comment by rootCBR** [comment]
Right, that's what brought me here. Please forgive my confusion, while I'm somewhat familiar with programming, this is the first time I've ever started to focus on one in particular.
Thanks for your quick reply, I think for now I'm just gonna focus on other areas of my project.

**Comment by sonoro1234** [comment]
> > I have the generated output files of cimgui which I specified to use the Imnodes extension
> 
> How exactly did you did that?

I am asking that because it is in fact possible to use cimgui for achieving the same with other imgui extensions (as done in cimguizmo, cimplot or cimguizmo_quat). Also because I was interested in wrapping one of the imgui nodes implementations althought I still dont know which one would be better to choose.

**Comment by rootCBR** [comment]
I simply put the Imnodes source and header file into cimgui/imgui/examples, renamed them to "imgui_impl_imnodes", and added "imnodes" as implementation to generate in configurator.bat.

**Comment by sonoro1234** [comment]
If you tell me which of all imnodes extensions you are interested in, I could do the C wrapping but it would remain the work to go from C to C#.

**Comment by rootCBR** [comment]
Thanks, I'd appreciate that. [This](https://github.com/Nelarius/imnodes) is the Imnodes extension I was looking to use.
What goes into making this usable in C#? Does it take a lot of work? I'm sure I'll be able to finish this one way or another.

**Comment by sonoro1234** [comment]
> What goes into making this usable in C#? Does it take a lot of work?

I am not a C# programmer so I really dont know. But surely you are already using imgui in C# provided by someone, (perhaps https://github.com/mellinoe/ImGui.NET ?) You should ask them for this task.
Meanwhile you could try to wrap in C# any of the modules provided in https://github.com/cimgui as there are some people interested.

**Comment by sonoro1234** [comment]
Just created https://github.com/cimgui/cimnodes

**Comment by sonoro1234** [comment]
closing this issue as it is plenty of not related info
