### ISSUE TITLE
Problem compiling the library

### ISSUE THREAD

**Issue by davidgm94** [cimgui/cimgui#136]
Hello Víctor,

Congrats for the project! I have been having a problem yesterday when using your library:

When I define `CIMGUI_DEFINE_ENUMS_AND_STRUCTS`, I get a number of errors of this type.
```
1>In file included from src\ext\cimgui\cimgui.cpp:7:
1>src\ext\cimgui/cimgui.h(210,16): error : redefinition of 'ImVector' as different kind of symbol
1>src\ext\cimgui/./imgui/imgui.h(1301,8): message : previous definition is here
```

This is a compilation using Visual Studio 2019 and LLVM-Clang CL. I am just compiling the library alone.

Am I doing something wrong?

Thank you very much for your work, it's really nice to have. I hope I can use it soon :)

**Comment by sonoro1234** [comment]
Did you tried with last master or docking_inter branches?

**Comment by davidgm94** [comment]
> For compiling the library (without implementations) the model would be https://github.com/cimgui/cimgui/blob/master/CMakeLists.txt . Here you will see that you should not define `CIMGUI_DEFINE_ENUMS_AND_STRUCTS`
> For compiling a program using the library the model is: https://github.com/cimgui/cimgui/blob/master/test/CMakeLists.txt
> For setting it to work with implementations see: #135
> 
> Solved?

Solved. The problem was that I wasn't understanding how to compile it properly. Now it compiles without errors. Thanks for the quick answer and the help :)
