### ISSUE TITLE
Metadata saying whether a function is internal or not.

### ISSUE THREAD

**Issue by Dominaezzz** [cimgui/cimgui#139]
Would it be possible to add a JSON field saying whether a function is internal or not?
Now that `imgui_internal` is included by default my code generation for `kotlin-imgui` broke.

**Comment by sonoro1234** [comment]
I will try althought it has some complications. 
Meanwhile you can generate without imgui_internal: `luajit ./generator.lua gcc false glfw opengl3 opengl2 sdl`
How is kotlin-imgui broken by internal addition?

**Comment by Dominaezzz** [comment]
Thanks for the quick response!
Yes the location info solves the problem! Thanks!

With regard to how it breaks, for apis like `pushID` and `popID`, I generate a convenience function `withID`. Which allows users to just do,
```
withID("MagicID") {
    // Other imgui stuff
}
```
instead of,
```
pushID("MagicID")
try {
    // Other imgui stuff
} finally {
    popID()
}
```

I had initially assumed that every push would have a pop and every begin would have an end.
This was not the case anymore with the addition of the internal apis.
Right now I have a blacklist of these functions, so I guess that's fine.

`igImTriangleBarycentricCoords` is the real issue, as it has C++ `float&` which should be exposed as `float*` in C. It needs to be hand written like these https://github.com/cimgui/cimgui/blob/affd97cd32995c64278b975487450fa5c7b42299/generator/output/cimgui.h#L3108 .

**Comment by sonoro1234** [comment]
> `igImTriangleBarycentricCoords` is the real issue, as it has C++ `float&` which should be exposed as `float*`

Could you please open a new issue for that?

Closing issue solved by https://github.com/cimgui/cimgui/commit/a27b5236dbdc34ef33583739d4907ae104b630b9 and two following commits

**Comment by sonoro1234** [comment]
@Dominaezzz  not need to open a new issue: already solved, now both branches convert non const references to pointer.

Please dont doubt to open issues on any small modification needed to ease bind making.
