### ISSUE TITLE
Incorrect return type for ImVec2ih constructor

### ISSUE THREAD

**Issue by lmariscal** [cimgui/cimgui#141]
I'm a little uncertain here, but I believe that the `explicit` type is no the correct type.

https://github.com/cimgui/cimgui/blob/master/generator/output/definitions.json#L9028

And in the main header `cimgui.h` the return type is `ImVec2ih*`

https://github.com/cimgui/cimgui/blob/bc3bc4583d0e857c05d0d76e9275c7a0652108f1/cimgui.h#L2449

**Comment by sonoro1234** [comment]
Thanks!!
correction pushed

I am so surprissed: How can you catch all this errors lost in 10000 lines of json?

**Comment by lmariscal** [comment]
> Thanks!!
> correction pushed
> 
> I am so surprissed: How can you catch all this errors lost in 10000 lines of json?

Well, my Nim generator for ImGui bindings uses the provided json to create the bindings, so I check if it fails to compile/generate and have to go hunt for this little issues.

But thank you for fixing this stuff and also in such a short amount time!
