### ISSUE TITLE
Location data for structs (and enums too if possible)

### ISSUE THREAD

**Issue by Dominaezzz** [cimgui/cimgui#142]
Can we get the same location data for structs as we do for functions?

**Comment by sonoro1234** [comment]
And for enums also

**Comment by Dominaezzz** [comment]
Regarding structs.
I just figured out that I can infer a structs location from it's member function's location (the ctor, to be specific).
So I guess that one can be skipped? Or maybe a separate JSON array.

**Comment by Dominaezzz** [comment]
Never mind. Edge case, `ImGuiGroupData` doesn't have a ctor defined in cimgui.

**Comment by sonoro1234** [comment]
The same happens with enums, each enum value is an array.
Sepárate JSON collection with keys being struct or enums names and values are location is a solution that does not break binding generators, but it is also more cumbersome to generate and use

**Comment by sonoro1234** [comment]
I have implemented the separate JSON  collection solution being the non breaking change
