### ISSUE TITLE
structs_and_enums.json does not contain all structure types

### ISSUE THREAD

**Issue by CallumDev** [cimgui/cimgui#145]
`ImGuiInputTextState` has a member of type `STB_TexteditState`, but the information for `STB_TexteditState` is not in the output json. 

This breaks generating bindings from json that include internals

**Comment by sonoro1234** [comment]
In cimgui.h you have the struct info
```c
typedef struct
{
   int cursor;
   int select_start;
   int select_end;
   unsigned char insert_mode;
   unsigned char cursor_at_end_of_line;
   unsigned char initialized;
   unsigned char has_preferred_x;
   unsigned char single_line;
   unsigned char padding1, padding2, padding3;
   float preferred_x;
   StbUndoState undostate;
} STB_TexteditState;
```

It was not my intention to provide all struct information outside imgui.h and imgui_internal.h (as GLFWwindow for example)
In LuaJIT-ImGui I am also using cimgui.h to provide some C info and structs_and_enums.json to make the class generation.

**Comment by sonoro1234** [comment]
But STB_TexteditState and others are now included!!
