### ISSUE TITLE
Freetype for fonts

### ISSUE THREAD

**Issue by RUSshy** [cimgui/cimgui#146]
Hi

Is it possible to use freetype instead for the fonts? or at least expose the API 

The default option is very blurry on custom fonts

https://github.com/ocornut/imgui/tree/master/misc/freetype

**Comment by sonoro1234** [comment]
I cant have generated every possible imgui branch, option etc.
Just having to generate master and docking branch duplicates my efforts (I am wishing that docking gets merged on master)

I should be easy to generate: Do as imgui says and regenerate but manually writing the only function and enum needed.

The other possibility would be to change generator.lua for taking function and enum from  imgui_freetype.h:

lines 339,340 and 341

```Lua
	save_data("headers.h",[[#include "../imgui/imgui.h" 
	#include "../imgui/imgui_internal.h"]])
	parser1 = parseImGuiHeader([[headers.h]],{[[imgui]],[[imgui_internal]],[[imstb_textedit]]})
```

should now be

```Lua
	save_data("headers.h",[[#include "../imgui/imgui.h" 
	#include "../imgui/imgui_internal.h"
         #include "../imgui/misc/freetype/imgui_freetype.h"]])
	parser1 = parseImGuiHeader([[headers.h]],{[[imgui]],[[imgui_internal]],[[imstb_textedit]],[[imgui_freetype]]})
```

**Comment by RUSshy** [comment]
I understand, i think it could be done separatly to avoid maintenance burden

but thanks, i'll give it a try, and send a PR if i manage to make something easy to maintain

**Comment by sonoro1234** [comment]
Any suggestions are welcome!!

**Comment by sonoro1234** [comment]
@RUSshy I have just added an option in generator.bat (sh) for including imgui_freetype.h and modified CMakeLists.txt to build it with an option

**Comment by sonoro1234** [comment]
closing now as issue is solved
