### ISSUE TITLE
docking

### ISSUE THREAD

**Issue by luke-titley** [cimgui/cimgui#148]
Hey, I just wanted to check. is the docking_inter branch a branch that is synced up with the imgui docking branch?
No worries if not. Just curious about what it is, as it would love to use cimgui with docking branch.

Thanks!

**Comment by sonoro1234** [comment]
Yes, it is synced with last tagged imgui docking branch

**Comment by luke-titley** [comment]
oh, brilliant. Thank you!

**Comment by sonoro1234** [comment]
Remember that you can pull any imgui branch or commit and generate again

**Comment by luke-titley** [comment]
Yes thank you. Just figuring it out now. Seems nice and simple.
