### ISSUE TITLE
Add file:line information for each definition (an extension upon "locations")

### ISSUE THREAD

**Issue by oprypin** [cimgui/cimgui#151]
This is related to https://github.com/cimgui/cimgui/issues/142 – I see that an "imgui"/"internal" distinction was introduced. But it seems like a more general approach would be to just present the file name itself, and users could just check `!= "imgui.h"` themselves for to find if it's "internal".

But a really nice (for me, anyway) addition that I am asking on top of this is to show also the line number where a definition occurred. I assume that the parser has this information available to it, it'd just need to be exposed.

For example, [`SetNextWindowSize` is in `imgui.h`:`310`](https://github.com/ocornut/imgui/blob/v1.78/imgui.h#L310)

Lacking this, I was considering resorting to parsing imgui.h again myself (using `ctags` or even my own regexps) to reconstruct this information.
[**That *did* work**](https://github.com/oprypin/crystal-imgui/commit/f55d8779c5cdd27bee594b306c33c29d38e2b2f2) but in the end I decided that this is too hacky and even then will often break for others with a different ctags version.

The reason that I'm doing this is that for my bindings to another programming language it's not good that there's no [API documentation](https://oprypin.github.io/crystal-imgui) whatsoever, and I'm not about to write it myself. By getting the code location for each definition I could

1. at least link to the corresponding definition in the C++ header file which has doc comments;
2. perhaps try to somehow make sense of comments around the definition and automatically paste those into the documentation of my bindings.

**Comment by sonoro1234** [comment]
My main problem with keeping line information is that althought I have it from the preprocessor, I am losing it in afterwards in the parsing process: I merge all lines again in order to apply regular expressions to the whole text so that I can extract first outer entities (namespace, struct,...) as a whole and then apply regular expressions again to this outer entities until the final inner entities are reached.

If the main reason for wanting line numbers is to get comments from the C++ header, perhaps a workaround is just keeping this comments in the parsing process. I am going to give it a try.

**Comment by oprypin** [comment]
>  merge all lines

Having found an entity, couldn't you count the number of '\n' characters before its character position?

> just keeping this comments in the parsing process.

OK so you'll keep them, but then what? I don't think it's possible to put those into the generator output in any useful way. The comments aren't machine-readable at all!

> If the main reason for wanting line numbers is to get comments from the C++ header

Not really. It's just one reason, there could be many more (I already have one -- for the ability to directly link to the C++ headers).

**Comment by sonoro1234** [comment]
> Having found an entity, couldn't you count the number of '\n' characters before its character position?
>Not really. It's just one reason, there could be many more (I already have one -- for the ability to directly link to the C++ headers).

Seems tricky but I will have a look on that.


> OK so you'll keep them, but then what? I don't think it's possible to put those into the generator output in any useful way. The comments aren't machine-readable at all!

I have just pushed `comments` branch so you can take a look to see if this is useful for you.

**Comment by oprypin** [comment]
Thanks for that branch - https://github.com/cimgui/cimgui/compare/docking_inter...comments - it can even help me familiarize with the project.

I do see a problem, though.

> The comments aren't machine-readable at all!

https://github.com/ocornut/imgui/blob/v1.78/imgui.h#L391-L395


https://github.com/cimgui/cimgui/compare/docking_inter...comments#diff-b71de5e02bf079ee7168c1296dcbaf59R15846

What I meant is, there isn't always a strict mapping between a comment and the thing that precedes it.
Like here the comment spans 5 lines and applies to all 5 of the functions, but a simple extraction method just gives chunks of that without any context. And a complex extraction method a) shouldn't be your burden and b) won't satisfy everyone

**Comment by sonoro1234** [comment]
So I will merge to master the file:line changes and will drop comments.

Still left to comment if repaired defaults (issue #150) are ok:
now `(((ImU32)(255)<<24)|((ImU32)(255)<<16)|((ImU32)(255)<<8)|((ImU32)(255)<<0))` is just `4294967295` is that ok?

**Comment by oprypin** [comment]
Yes I think that's OK. Thanks.
Is there already a branch with the code changes, by the way?

**Comment by oprypin** [comment]
@sonoro1234 Some issues I see on https://github.com/cimgui/cimgui/compare/docking_inter...comments.

* "defaults": value used to be always string, but now it's integer-or-string, that's probably not good.

  https://github.com/cimgui/cimgui/blob/7685bab86f4ba61931a9713d592d4e08e812d88e/generator/output/definitions.json#L444

* Some items that used to have a `location`, now lost it altogether.

  https://github.com/cimgui/cimgui/blob/7685bab86f4ba61931a9713d592d4e08e812d88e/generator/output/definitions.json#L15841

**Comment by oprypin** [comment]
Another one

* ```diff
  -        "rounding_corners": "ImDrawCornerFlags_All"
  +        "rounding_corners": 15
  ```

**Comment by oprypin** [comment]
I pushed the diff that I'm getting with this here: https://github.com/oprypin/crystal-imgui/commit/d363a6658e44483bdabb8c78a6004ca5061c8836#diff-73ec3622313ef7186f13c32e06204f22 (the base is what I was getting with ctags). But part of the diff is unrelated, I didn't work around #152 in the new diff any more. Maybe it will help you spot something more. (see the file obj.cr)

**Comment by oprypin** [comment]
I also think some line numbers were determined incorrectly – you can find those in the diff as well, e.g.
```diff
-  # [[View C++ header](https://github.com/ocornut/imgui/blob/v1.78/imgui.h#L418)]
+  # [[View C++ header](https://github.com/ocornut/imgui/blob/v1.78/imgui.h#L419)]
```
for `igGetIDStr(char*)`

**Comment by sonoro1234** [comment]
Comments make appear some errors with line numbers. Now pushed to comments branch and seems corrected

**Comment by oprypin** [comment]
Pushed a new diff.
https://github.com/oprypin/crystal-imgui/commit/426acaba758f6e1039d48e36b9570b83708889aa#diff-73ec3622313ef7186f13c32e06204f22

Overall, looking *very good*. But I commented on #150 about one small problem, and there's another small problem for the purposes of *this* issue.

`igPopClipRect` is detected as being at https://github.com/ocornut/imgui/blob/v1.78/imgui.h#L2095
but actually `ImDrawList_PopClipRect` is on that line.

Same for `igEnd` - its position is overwritten with the position of  `ImGuiListClipper_End`.

**Comment by sonoro1234** [comment]
Should be fixed now
