### ISSUE TITLE
Impossible to distinguish actual destructors from default destructors

### ISSUE THREAD

**Issue by oprypin** [cimgui/cimgui#152]
Example:

* https://github.com/cimgui/cimgui/blob/060df0f4eb526044fa95f23b7ce2f321ef3d71e7/generator/output/definitions.json#L983-L1001

  – [is a destructor with an important body](https://github.com/ocornut/imgui/blob/95c99aaa4be611716093edcb6b01146ab9483f30/imgui.h#L2028).

* https://github.com/cimgui/cimgui/blob/7685bab86f4ba61931a9713d592d4e08e812d88e/generator/output/definitions.json#L563-L581

  – default constructor, has no body; the type is just a data bag.

But I think, sadly, these are not possible to distinguish (I'd expect "real" destructors to have, for example, their "location" filled in).

In a garbage-collected programming language for the latter I never need to call destroy() and for performance reasons it's important for me to distinguish situations when I can skip these finalizers.

**Comment by sonoro1234** [comment]
the bodies in cimgui.cpp are

```C++
CIMGUI_API void ImDrawListSplitter_destroy(ImDrawListSplitter* self)
{
    IM_DELETE(self);
}

CIMGUI_API void ImColor_destroy(ImColor* self)
{
    IM_DELETE(self);
}
```

>(I'd expect "real" destructors to have, for example, their "location" filled in).

file:line issues should be in #151 (they did not have location field in previous versions also)

**Comment by oprypin** [comment]
> the bodies in cimgui.cpp are

I know, but I am not interested in bodies that only invoke a trivial default destructor of C++, which simply frees memory. [It's a no-op for me](https://github.com/oprypin/crystal-imgui/blob/f43dfdf66ebad2ea3b6c12b56781923aa5a5198f/src/imgui.cr#L4) and I really want to skip it, unless the destructor performs some actual additional cleanup upon destruction.

> file:line issues should be in #151 (they did not have location field in previous versions also)

This is a bit contradictory. "They did not have location field in previous versions" is indeed what I see as the problem, it would be there regardless of the resolution of issue #151

**Comment by sonoro1234** [comment]
> This is a bit contradictory. "They did not have location field in previous versions" is indeed what I see as the problem, it would be there regardless of the resolution of issue #151

Yes, I will add these locations also

**Comment by oprypin** [comment]
I have tried out with merged changes, and it is great! Thanks.

I just have one comment. The presence of the field "realdestructor" 100% matches the presence of fields "destructor"+"location". I understand that you added it in response to this issue, but you also fixed the "locations" field to actually be present when appropriate, and that is enough by itself. If I were you, I'd drop "realdestructor", but of course it's entirely up to you.

**Comment by sonoro1234** [comment]
If something fails it allows checking
