### ISSUE TITLE
custom imgui_impl_sdl.c implementation

### ISSUE THREAD

**Issue by MrcSnm** [cimgui/cimgui#156]
Hello, I'm writing a binding to D and everything has worked fine till I decided using multiviewports.

I'm using OpenGL3 impl + SDL impl

I believe that there is some kind of problems right now on `ImGuiViewportP` and `ImGuiViewport`.
In the original code, `struct ImGuiViewportP : ImGuiViewport`, and on the `ImGui::UpdatePlatformWindows` we are using `ImGuiViewportP`.

There is a problem that ImGuiViewportP is passed as an argument for PlatformCreateWindow.
When assigning the platform user data onto the viewport, it assigns correctly inside the CreateWindow call.
But when it arrives the next function `SetWindowTitle` the `PlatformUserData` becomes null. AFAIK I'm allocating memory on the heap using `igMemAlloc` for the `PlatformUserData`.

Putting that aside, I can see that between `SetWindowTitle` and  `SetWindowSize`, my viewport address suddenly changes

**Comment by sonoro1234** [comment]
I am not sure to understand: ImGui::UpdatePlatformWindows does not take any argument.

For using backends you should first try the easy path: (as explained in https://github.com/cimgui/cimgui/issues/135) use the functions provided from imgui_impl_sdl and imgui_impl_opengl3 (you should add this two cpp files to the compilation) to remake what is done in example_sdl_opengl3/main.cpp.

 Only when this is working and if it is not enough for your needs you could implement yourself the functions provided in imgui_impl_sdl and imgui_impl_opengl3.

**Comment by MrcSnm** [comment]
PlatformCreateWindow is from PlatformIO callback registration

I'm using the examples shown in the backends folder, the only difference is some adaptations for language specifix syntax and the `#define` used.

Do you mean generating a DLL including impl_sdl and impl_gl3?

**Comment by sonoro1234** [comment]
> Do you mean generating a DLL including impl_sdl and impl_gl3?

Yes, and then just use the function shown in https://github.com/cimgui/cimgui/blob/master/generator/output/cimgui_impl.h
In LuaJIT-ImGui https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/lua/imgui/glfw.lua#L116 is used in https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/lua/imgui/window.lua#L90 and https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/lua/imgui/window.lua#L146

**Comment by MrcSnm** [comment]
Just remembered right now that I'm using some alternative open gl loader library.

I'm testing right now with the DLL (but only included impl_sdl, don't know if it possible)

It is giving a bug right now at `ImGui_ImplOpenGL3_RenderWindow`
Reason: Receiving a null viewport

**Comment by sonoro1234** [comment]
I have just added backend_test folder in the docking_inter branch. You only need to provide to cmake `SDL_PATH` with the path where SDL2 cmake install is done (or leave it empty `-DSDL_PATH=""` if it is in a folder already watched from cmake)
It will generate `cimgui_sdl` module and `test_sdl` executable that will use it from C

**Comment by sonoro1234** [comment]
> It is giving a bug right now at `ImGui_ImplOpenGL3_RenderWindow`
> Reason: Receiving a null viewport

In order to values your claims I would need to see the code. It should be C code as I cant assess D code. You could begin with backend_test and after it is working for you  implement in C imgui_impl_opengl in order to see what is happening.

**Comment by MrcSnm** [comment]
Testing right now, I saw that I won't be able to use impl_opengl3 because of the `Init` function, where it has the `InitPlatformInterface`.
As I have to do my own open gl load.

The other problem was that I wasn't able to compile using your CMakeLists, because my SDL folder had some inexistent `SDLTargets.cmake`.

**Comment by MrcSnm** [comment]
@sonoro1234 Solved the problem!

By viewing my debugger right now, I saw that viewport is receiving null, while the void* user data is receiving the data meant to be on viewport
![dbg](https://user-images.githubusercontent.com/10136262/96338382-79a9f700-1042-11eb-8f0f-f0d8155cd82e.png)

**Comment by sonoro1234** [comment]
> Testing right now, I saw that I won't be able to use impl_opengl3 because of the `Init` function, where it has the `InitPlatformInterface`.
> As I have to do my own open gl load.

It can be changed afterwards. First lets focus on building backend_test.

> The other problem was that I wasn't able to compile using your CMakeLists, because my SDL folder had some inexistent `SDLTargets.cmake`.

This is caused by not having a SDL2 correctly built with cmake. I have used https://github.com/SDL-mirror/SDL.git

> By viewing my debugger right now, after so much time looking closely at it I saw that viewport is receiving null, while the void* user data is receiving the data meant to be on viewport

That is very weird!!. Please finish the standard backend_test building. When it works change it by adding your imgui_impl_sdl.c instead of the original one. If it fails I will be able to see what are you doing exactly.

**Comment by MrcSnm** [comment]
I finished converting my code from D to cpp, and it seems to be giving the same error on the same line, I tried to keep the most close from my D code.

The file must be located on cimgui/
As it is importing from `generator/output/cimgui_impl.h`


[impl_sdl.zip](https://github.com/cimgui/cimgui/files/5398849/impl_sdl.zip)

**Comment by MrcSnm** [comment]
I have took the same code from imgui repo and basically replaced with cimgui func style but it is still giving the same error:


I believe you will prefer testing this version than the other as the other is the conversion from my D code while that is the conversion from imgui implementation
[impl_sdl_plain.zip](https://github.com/cimgui/cimgui/files/5399903/impl_sdl_plain.zip)

**Comment by sonoro1234** [comment]
It runs without errors compiling with mingw (probably with gcc in linux) but fails with MSVC. It is related with two functions returning UDT (user data type) which are not C compatible. They are ImGui_ImplSDL2_GetWindowSize and ImGui_ImplSDL2_GetWindowPos both returning ImVec2.

Look for CimguiStorage in cimgui.cpp where there is a mechanism to set two hooks for that. For example `ImGuiPlatformIO_Set_Platform_GetWindowPos` takes a function returning void and having an argument `ImVec2* out_pos`

**Comment by MrcSnm** [comment]
So, I've test in D and it everything worked!

I prefer using my custom one because I have support for the non viewport branch too, while I don't think I'll use it any time soon, and it is better for debugging having available the code on the main language.

Sometimes I work on homebrew games/things, so, I believe it would be better having accessibility to the underlying implementation.

---

Can you take some time to explain me why this data is not supported though?
ImVec2 was something I believe was so simple and yet caused all that problem, why?

**Comment by MrcSnm** [comment]
Btw, that SDL compiling command, is that from any README file or you read the CMakeLists for that? I had no clue that there was something like that and that was needed

**Comment by MrcSnm** [comment]
> `@REM Build for Visual Studio compiler. Run your copy of vcvars32.bat or vcvarsall.bat to setup command-line compiler.

cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DBUILD_SHARED_LIBS=on -DCMAKE_INSTALL_PREFIX="install"  SDLrepositorypath

cmake --build . --target install`

Although I didn't needed to run vcvarsall nor NMake Makefiles

**Comment by sonoro1234** [comment]
If you mean the first line it is from https://github.com/ocornut/imgui/blob/master/examples/example_sdl_opengl3/build_win32.bat

**Comment by MrcSnm** [comment]
> If you mean the first line it is from https://github.com/ocornut/imgui/blob/master/examples/example_sdl_opengl3/build_win32.bat

Acutally I meant the SDL building line with the defines

**Comment by sonoro1234** [comment]
The other lines are just cmake commands
