### ISSUE TITLE
Tables in Dear ImGui 1.80

### ISSUE THREAD

**Issue by ocornut** [cimgui/cimgui#163]
FYI, I am expecting to merge tables in master and release 1.80 in 2~3 weeks hopefully.
Letting you know ahead so you can check if cimgui works with the additions in that branch.

**Comment by sonoro1234** [comment]
Thanks for advice!!

**Comment by epezent** [comment]
Fixed! Been a while since I updated my tables branch, so I missed the change to `TableHeadersRow`. This reminds me that I should really setup up CI for ImPlot.

**Comment by sonoro1234** [comment]
All have been correctly tested with imgui tables.
