### ISSUE TITLE
How to deal with imconfig.h switches?

### ISSUE THREAD

**Issue by frink** [cimgui/cimgui#164]
In order to have full unicode support `#define IMGUI_USE_WCHAR32` needs to be set. This changes `ImWchar` from `ImWchar16` to `ImWchar32`. However, in `cimgui.h` it is hard coded as `ImWchar16`...

How do we deal with stuff like this?

**Comment by sonoro1234** [comment]
use that define and do generation to get new cimgui.h

**Comment by frink** [comment]
I see. Thanks.

I'm using git submodules to include my code. I guess I'll have to make those modifications in my own fork since submodules do not allow uncommitted modifications. Either that or script the changes when I generate the new cimgui.h...

Also, is there any documentation on how to do the generation for third party widgets? (I know there is ImPlot...) I'm thinking about what is the best way to deal with code management all the way around...

**Comment by oprypin** [comment]
You can just `#define ImWchar ImWchar16`

**Comment by frink** [comment]
> You can just #define ImWchar ImWchar32

Where would I do that? Before or after including cimgui.h

**Comment by oprypin** [comment]
For Dear ImGui code, yes, you likely need to also use `IMGUI_USE_WCHAR32`. Although this hack is "stronger", i.e. would probably override that define's effect so you might not even need it (though only by chance).

And then yes, of course you define that before including `cimgui.h`. But you need to do it **every time** you include `cimgui.h`. Hm first I thought you could achieve this by simply putting it into your `imconfig.h`. But then I realized, no, `cimgui.h` doesn't include `imgui.h`.

**Comment by frink** [comment]
Another suggestion from the ImGui Discord was to use the `-DIMGUI_USER_CONFIG=myconfig.h` flag build process. This is probably more elegant and easier from the point of build system maintenance and keeps less brittle dependencies between repos. Wondering if there is a way to pass this through your `generator.lua`...?

**Comment by oprypin** [comment]
`IMGUI_USER_CONFIG` is what I meant when saying `imconfig.h`. See caveats.

**Comment by frink** [comment]
From talking more with @oprypin on Discord I'm inclined to think that generator.lua needs to be able to take switches so that we can pass `-DIMGUI_USER_CONFIG=myconfig.h` or else the generated cimgui.h needs to maintain the define logic for at least the case of `#define IMGUI_USE_WCHAR32` but probably others too. Seems simpler to allow flags to be passed.

**Comment by oprypin** [comment]
Yes actually doesn't look like it's easily configurable.

First I tried this but it doesn't work:

<details>

```diff
diff --git a/generator/generator.sh b/generator/generator.sh
index efb48b373..bff1bcf33 100755
--- a/generator/generator.sh
+++ b/generator/generator.sh
@@ -16,4 +16,4 @@
 # arg[2] options as words in one string: internal for imgui_internal generation, freetype for freetype generation
 # examples: "" "internal" "internal freetype"
 # arg[3..n] name of implementations to generate
-luajit ./generator.lua gcc "internal" glfw opengl3 opengl2 sdl
+luajit ./generator.lua 'gcc -DIMGUI_USE_WCHAR32' "internal" glfw opengl3 opengl2 sdl
```

</details>

This is the least intrusive change I was able to make:

```diff
diff --git a/generator/generator.lua b/generator/generator.lua
index fbcd30911..c0443052b 100644
--- a/generator/generator.lua
+++ b/generator/generator.lua
@@ -10,7 +10,7 @@ local INTERNAL_GENERATION = script_args[2]:match("internal") and true or false
 local FREETYPE_GENERATION = script_args[2]:match("freetype") and true or false
 local CPRE,CTEST
 if COMPILER == "gcc" or COMPILER == "clang" then
-    CPRE = COMPILER..[[ -E -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_API="" -DIMGUI_IMPL_API="" ]]
+    CPRE = COMPILER..[[ -DIMGUI_USE_WCHAR32 -E -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_API="" -DIMGUI_IMPL_API="" ]]
     CTEST = COMPILER.." --version"
 elseif COMPILER == "cl" then
     CPRE = COMPILER..[[ /E /DIMGUI_DISABLE_OBSOLETE_FUNCTIONS /DIMGUI_API="" /DIMGUI_IMPL_API="" ]]
```

And it does work:

```diff
diff --git a/cimgui.h b/cimgui.h
index 18d844a59..61757b753 100644
--- a/cimgui.h
+++ b/cimgui.h
@@ -162,7 +162,7 @@ typedef int (*ImGuiInputTextCallback)(ImGuiInputTextCallbackData* data);
 typedef void (*ImGuiSizeCallback)(ImGuiSizeCallbackData* data);
 typedef unsigned short ImWchar16;
 typedef unsigned int ImWchar32;
-typedef ImWchar16 ImWchar;
+typedef ImWchar32 ImWchar;
 typedef signed char ImS8;
 typedef unsigned char ImU8;
 typedef signed short ImS16;
@@ -1027,7 +1027,7 @@ struct ImFont
     float Scale;
     float Ascent, Descent;
     int MetricsTotalSurface;
-    ImU8 Used4kPagesMap[(0xFFFF +1)/4096/8];
+    ImU8 Used4kPagesMap[(0x10FFFF +1)/4096/8];
 };
 struct StbUndoRecord
 {
```

If you're willing to maintain your generated cimgui, might as well also maintain this edit to the file...........

I still think the defines are easier.

**Comment by frink** [comment]
Okay. I'mg going to close this because talking through things helped me figure it out and lead to PR #165. This is the right way to solve such problem and allows a host of other functionality.

**Comment by sonoro1234** [comment]
> But you need to do it **every time** you include `cimgui.h`. Hm first I thought you could achieve this by simply putting it into your `imconfig.h`. But then I realized, no, `cimgui.h` doesn't include `imgui.h`.

cimgui.h generated with `#define IMGUI_USE_WCHAR32` in imconfig.h wont need to require imgui.h to use WCHAR32 because generation has already maked the changes.

cimgui.cpp does include imgui.h

**Comment by sonoro1234** [comment]
> Also, is there any documentation on how to do the generation for third party widgets? (I know there is ImPlot...) I'm thinking about what is the best way to deal with code management all the way around...

if imconfig.h is changed all the third party widgets will found the change in generation and compilation.
the documentation is in generator.bat in every widget repository.
