### ISSUE TITLE
64-bits enums

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#170]
@mellinoe @oprypin @lmariscal @Gekkio @Dominaezzz @ThisDrunkDane @Gnimuc @thomcc @ctreffs @vaiorabbit
and any other interested:

According to https://github.com/sonoro1234/LuaJIT-ImGui/issues/23#issuecomment-744586544

Due to the big number of enums needed by imgui they could be created in the near future as 64-bits enums as in:

```cpp
enum ImGuiWindowFlags_ : ImS64
{
    ImGuiWindowFlags_None                   = 0,
    ImGuiWindowFlags_NoTitleBar             = 1LL << 60,// Disable title-bar
```

In order to make it C compilable in all supported compilers it would be generated by cimgui as

```c
typedef enum {
   ImGuiWindowFlags_None                   = 0,
  ...
} ImGuiWindowFlags_ ;
static const ImS64 ImGuiWindowFlags_NoTitleBar = 1LL << 60;
```
enumtypes table would be added to structs_and_enums for enums with size bigger than 4 bytes as in:
structs_and_enums.enumtypes["ImGuiWindowFlags_ "] = "ImS64"

and calc_value for ImGuiWindowFlags_NoTitleBar would be a string `"1152921504606846976ULL"` instead of a number so that it can be recognized by the binder.

Any caveats from binding generators are requested regarding
- C issues
- You binding language issues

**Comment by thomcc** [comment]
Hmm, so, the two examples you gave are different. E.g. if `enum ImGuiWindowFlags_ : ImS64` will mean passing an `ImGuiWindowFlags_` is equivalent to passing a 64 bit integer, and in the 2nd example it would be passing an `int` (typically 32 bits).

IIRC this has a meaningful difference on x86_64, since the upper bits of the register the 32-bit value is passed in doesn't need to be cleared.

That said, having all the functions that accept the enumeration take a ImS64 would avoid this.

(From the bindings side, it will be slightly annoying to support in the Rust bindings generator, but not too bad)

**Comment by sonoro1234** [comment]
> IIRC this has a meaningful difference on x86_64, since the upper bits of the register the 32-bit value is passed in doesn't need to be cleared.

I am not sure to understand.

This would be the cimgui definitions
```c
typedef ImS64 ImGuiWindowFlags;
CIMGUI_API bool igBegin(const char* name,bool* p_open,ImGuiWindowFlags flags)
{
    return ImGui::Begin(name,p_open,flags);
}
```

**Comment by thomcc** [comment]
Ah, that's fine then.

**Comment by mellinoe** [comment]
This will be pretty straightforward to handle in the C# binding.

**Comment by ThisDrunkDane** [comment]
For the Odin binding this should have little effect as well, the odin generator would just look a the `enumtypes` for the size.

**Comment by sonoro1234** [comment]
cimgui is already prepared for 64-bit emuns. At imgui 1.80 it is still not used.
@ocornut Will it be used in the future?

**Comment by ocornut** [comment]
Yes very probably, but not in near future. It just help me design current api knowing that we can potentially add new flags later and it won’t be a problem for languages like JS or LUA.

You can close this if you have all the tech ready.
