### ISSUE TITLE
cpp2ffi: mapping from line -> loca missing some structs

### ISSUE THREAD

**Issue by kevinw** [cimgui/cimgui#171]
The `par:insert` function in `generator/cpp2ffi.lua` makes a map from C definition to "location."

https://github.com/cimgui/cimgui/blob/414ad3f8f497c79491cc45e6a6a414ce8cac92e9/generator/cpp2ffi.lua#L943

When I run the generator, I get an error from line 374 saying `no entry in linenumdict` -- it's because my `linenumdict` has keys with a bunch of spaces on the end. This modification, to strip whitespace from the keys going into the table, fixes it for me:

```
		table.insert(cdefs,{line:gsub("^%s*(.-)%s*$", "%1"),loca})
```

**Comment by sonoro1234** [comment]
How are you getting this?:

Is this latest cimgui?
Which compiler?
Which imgui?

**Comment by sonoro1234** [comment]
fix pushed!!
Thanks
