### ISSUE TITLE
Strict c in cimgui.h headers

### ISSUE THREAD

**Issue by frett27** [cimgui/cimgui#173]
Hi, i try to import the c imgui header file from zig, that translate C code into zig definition, 
and i faced some C++ integration in cimgui.h file that fail this process.
as for Ada, or other external languages, that could natively import C definition in parsing them, is it an option to use some strict compilation in validation of the cimgui binding ?

some errors faced : 

./cimgtest.zig:1:12: error: C import failed
const ig = @cImport({
           ^
cimgui/imgui/imgui.h:178:39: note: must use 'struct' tag to refer to type 'ImGuiInputTextCallbackData'
typedef int (*ImGuiInputTextCallback)(ImGuiInputTextCallbackData* data);
                                      ^
cimgui/imgui/imgui.h:179:35: note: must use 'struct' tag to refer to type 'ImGuiSizeCallbackData'
typedef void (*ImGuiSizeCallback)(ImGuiSizeCallbackData* data);
                                  ^
cimgui/imgui/imgui.h:214:5: note: type name requires a specifier or qualifier
    ImVec2()                                { x = y = 0.0f; }
    ^
cimgui/imgui/imgui.h:214:13: note: expected ';' at end of declaration list
    ImVec2()                                { x = y = 0.0f; }
            ^
cimgui/imgui/imgui.h:227:5: note: type name requires a specifier or qualifier
    ImVec4()                                { x = y = z = w = 0.0f; }
    ^
cimgui/imgui/imgui.h:227:13: note: expected ';' at end of declaration list
    ImVec4()                                { x = y = z = w = 0.0f; }
            ^
cimgui/imgui/imgui.h:239:1: note: unknown type name 'namespace'
namespace ImGui
^
cimgui/imgui/imgui.h:239:16: note: expected ';' after top level declarator
namespace ImGui
               ^
cimgui/imgui/imgui.h:1369:1: note: 'inline' can only appear on functions
inline void* operator new(size_t, ImNewWrapper, void* ptr) { return ptr; }
^
cimgui/imgui/imgui.h:1369:22: note: expected ';' after top level declarator
inline void* operator new(size_t, ImNewWrapper, void* ptr) { return ptr; }
                     ^
cimgui/imgui/imgui.h:1457:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      WindowPadding;              // Padding within a window.
    ^
cimgui/imgui/imgui.h:1460:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      WindowMinSize;              // Minimum window size. This is a global setting. If you want to constraint individual windows, use SetNextWindowSizeConstraints().
    ^
cimgui/imgui/imgui.h:1461:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      WindowTitleAlign;           // Alignment for title bar text. Defaults to (0.0f,0.5f) for left-aligned,vertically centered.
    ^
cimgui/imgui/imgui.h:1467:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      FramePadding;               // Padding within a framed rectangle (used by most widgets).
    ^
cimgui/imgui/imgui.h:1470:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      ItemSpacing;                // Horizontal and vertical spacing between widgets/lines.
    ^
cimgui/imgui/imgui.h:1471:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      ItemInnerSpacing;           // Horizontal and vertical spacing between within elements of a composed widget (e.g. a slider and its label).
    ^
cimgui/imgui/imgui.h:1472:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      TouchExtraPadding;          // Expand reactive bounding box for touch-based system where touch position is not accurate enough. Unfortunately we don't sort widgets so priority on overlap will always be given to the first widget. So don't grow this too much!
    ^
cimgui/imgui/imgui.h:1484:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      ButtonTextAlign;            // Alignment of button text when button is larger than text. Defaults to (0.5f, 0.5f) (centered).
    ^
cimgui/imgui/imgui.h:1485:5: note: must use 'struct' tag to refer to type 'ImVec2'
    ImVec2      SelectableTextAlign;        // Alignment of selectable text. Defaults to (0.0f, 0.0f) (top-left aligned). It's generally important to keep this left-aligned if you want to lay multiple items on a same line.
    ^
./cimgtest.zig:7:9: note: referenced here
    _ = ig.igCreateContext(null);
        ^

**Comment by sonoro1234** [comment]
Did you remember setting `CIMGUI_DEFINE_ENUMS_AND_STRUCTS` ?

**Comment by frett27** [comment]
Yes, i settedup :
 zig build-exe -lc cimgui/cimgui.o cimgui/imgui/*.o cimgui/imgui/examples/imgui_impl_sdl.o -Icimgui/imgui -Icimgui/imgui/examples -I. -Icimgui -lc++ -DCIMGUI_DEFINE_ENUMS_AND_STRUCTS cimgtest.zig

but i was messedup by the backend implementation (sdl) that includes the natural imgui.h lib, that contains C++, naturally

**Comment by frett27** [comment]
now it works, thank's, my bad.
