### ISSUE TITLE
Errors when building latest commit

### ISSUE THREAD

**Issue by RogueMacro** [cimgui/cimgui#176]
I am trying to build cimgui with cmake on commit 6791a95. I get three errors when doing so.
```
cimgui.cpp(3377,47): error C2562: 'igAddContextHook': 'void' function returning a value
cimgui.cpp(4253,12): error C3861: 'ImFontAtlasBuildWithStbTruetype': identifier not found
cimgui.cpp(4273,12): error C3861: 'ImFontAtlasBuildRender1bppRectFromString': identifier not found
```

I guess these are edge cases, like igAddContextHook is the only function that returns void, but calls an imgui function that returns something else. I don't know what's up with the ImFontAtlasBuild.. It happens on both docking_inter and master.

**Comment by sonoro1234** [comment]
> cimgui.cpp(3377,47): error C2562: 'igAddContextHook': 'void' function returning a value

```C
CIMGUI_API void igAddContextHook(ImGuiContext* context,const ImGuiContextHook* hook)
{
    return ImGui::AddContextHook(context,hook);
}
```

Thats true, it shouldnt return a value. Its strange that this produces an error instead of a warning
Which is your compiler?

> cimgui.cpp(4253,12): error C3861: 'ImFontAtlasBuildWithStbTruetype': identifier not found

Thats strange, I cant reproduce, did you submodule update?

**Comment by RogueMacro** [comment]
Hi, I'm running Windows 10 64bit compiling with msvc. I'm trying to add support for tables to my bindings repo, but these errors are preventing me. If you want to look at the build.yml file, here it is: https://github.com/RogueMacro/imgui-beef/blob/master/.github/workflows/build.yml 

This is what clones cimgui and imgui:
```
git submodule update --init
cd cimgui
git checkout 3eec69f
git submodule update --init       
```

The reason I'm checking out 3eec69f is that 0d96f60 and later gives me linking errors when I compile. At first I believed it was a mistake of mine, but now I'm sure what is causing it. When using 0d96f60 and later, the compiler for the language I'm using gives me unresolved external symbols for the imgui table functions referenced in the cimgui table functions. Same goes for the backends. Running the exact same commands and cmake on 3eec69f however, does not.

**Comment by sonoro1234** [comment]
It would be much easier for me if you could test not with you build.yml but just a manual cmake build from latest cimgui (Which is not faling for me with msvc nmake)

**Comment by RogueMacro** [comment]
I'm sorry, it must have been my mistake. I can't reproduce the errors I got yesterday, but I'm still having some problems with the linking errors. I would really appreciate it if you could help me with those. They are errors like these:
```
cimgui.lib(cimgui.obj) : error LNK2019: unresolved external symbol "bool __cdecl ImGui::BeginTable(char const *,int,int,struct ImVec2 const &,float)" (?BeginTable@ImGui@@YA_NPEBDHHAEBUImVec2@@M@Z) referenced in function igBeginTable
cimgui.lib(imgui_demo.obj) : error LNK2001: unresolved external symbol "bool __cdecl ImGui::BeginTable(char const *,int,int,struct ImVec2 const &,float)" (?BeginTable@ImGui@@YA_NPEBDHHAEBUImVec2@@M@Z)
```

Those only happen on the latest commit and not previously.

**Comment by sonoro1234** [comment]
Yes, I can help but could you try with a manual cmake build please?

**Comment by RogueMacro** [comment]
I'm not sure what you mean? I can give you a list of the commands I just ran

**Comment by RogueMacro** [comment]
I'm building on my local computer

**Comment by RogueMacro** [comment]
Clone cimgui recursively and add these lines to cimgui.cpp:
```
#define CIMGUI_NO_EXPORT
#include "cimgui.h" // Already here
#include <generator/output/cimgui_impl.h>
```
Then I copy glfw, glad and KHR dependencies and my CMakeLists.txt file ([cimgui-dependencies.zip](https://github.com/cimgui/cimgui/files/5898035/cimgui-dependencies.zip)) to the directory then run these commands (in powershell):
```
cmake .
cmake --build . --target ALL_BUILD --config Debug -- /nologo /maxcpucount
```

**Comment by sonoro1234** [comment]
There are a lot of modifications to the standard cimgui (for example imgui_tables.cpp is missing)

A guide for making modifications including backends could be in backend_test folder or even https://github.com/sonoro1234/LuaJIT-ImGui

You should try to build the standard cimgui first and report result.

**Comment by RogueMacro** [comment]
@sonoro1234 What do you mean by "standard" cimgui? Is that just the master branch?

**Comment by sonoro1234** [comment]
> What do you mean by "standard" cimgui? Is that just the master branch?

Build without modifying anything from the repo

**Comment by RogueMacro** [comment]
Hi, I'm sorry that I bothered you it was actually my mistake. After imgui moved the backends from examples/ to backends/ I forgot to change the CMakeLists.txt file to account for that. It is all good now :+1:
