### ISSUE TITLE
Generate artifacts

### ISSUE THREAD

**Issue by amerkoleci** [cimgui/cimgui#179]
Hi,
Would be possible to have artifcacts generated from github workflows? 
Would come usefull having windows x64/x86 DLL's, macOS e Linux shared libraries.

Thanks

**Comment by sonoro1234** [comment]
A PR would be welcome, althought I wont be able to review it.
Only @rokups has made commits for workflows (also @lmariscal made some suggestions)

**Comment by Gnimuc** [comment]
We Julia guys use [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) for generating and releasing artifacts. This is [the script](https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/CImGui/build_tarballs.jl) for [the artifacts of cimgui](https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases).

**Comment by rokups** [comment]
Getting CI to store artifacts is trivial: https://github.com/actions/upload-artifact
A more complicated problem is generating useful artifacts. 
* What msvc runtime should dlls link to?
* What glibc version should .so link to? How would you force that when CI workers have a certain (definitely too new) glibc installed?
* I dont even know whats important on MacOS.

**Comment by sonoro1234** [comment]
> A more complicated problem is generating useful artifacts.

It seems reasonable.

**Comment by amerkoleci** [comment]
https://github.com/mellinoe/ImGui.NET/tree/master/deps/cimgui is using those dlls for C# interop

**Comment by sonoro1234** [comment]
> https://github.com/mellinoe/ImGui.NET/tree/master/deps/cimgui is using those dlls, so, dylib for C# interop

Yes, but he is a #C binding provider for cimgui
The different needs between binding providers is even more extended: which backend, if any, is needed in the dll?

**Comment by amerkoleci** [comment]
I'm not talking about ImGui backends (SDL, glfw) or rendering backends (d3d11, d3d12, etc), just about the DLL's.
Anyway I will add own artifacts generation in my repo.

Thank you :)

**Comment by sonoro1234** [comment]
> I'm not talking about ImGui backends (SDL, glfw) or rendering backends (d3d11, d3d12, etc), just about the DLL's.
> Anyway I will add own artifacts generation in my repo.
> 
> Thank you :)

My recomendation is to include backends in the DLL as done in LuaJIT-ImGui
