### ISSUE TITLE
Support for implot and imgui-node-editor

### ISSUE THREAD

**Issue by thetanil** [cimgui/cimgui#180]
Hey, I'm interested in integrating implot and imgui-node-editor in a imgui.net project. If I do this, I could do it by forking and extending cimgui if you had any desire to integrate these components here. If that is not interesting for cimgui, it would probably be easier for me to work with complete disregard for cimgui. I would be interested in some feedback from cimgui devs on this.

https://github.com/epezent/implot
https://github.com/thedmd/imgui-node-editor

p.s. thanks on the work you've all done so far!

**Comment by sonoro1234** [comment]
https://github.com/cimgui/cimplot is already done.
for imnodes there is already:
https://github.com/cimgui/cimnodes and https://github.com/cimgui/cimnodes_r

In no case they are added to https://github.com/cimgui/cimgui but they use it to generate.

https://github.com/thedmd/imgui-node-editor could be worked the same way althought it is more complex.

**Comment by thetanil** [comment]
This is great. Thank you very much for the information!
