### ISSUE TITLE
Compiling the static library with C

### ISSUE THREAD

**Issue by steadysupply** [cimgui/cimgui#183]
When I try to compile a C program with the static `cimgui` library, I see lots of
```
/usr/bin/ld: imgui_demo.cpp:(.text+0x168e0): undefined reference to `__cxa_guard_acquire'
/usr/bin/ld: imgui_demo.cpp:(.text+0x169b6): undefined reference to `__cxa_guard_release'
```
and compilation fails.

A minimal example to reproduce:

``` Makefile
# Makefile
all: init main ; ./main

init:
	git clone https://github.com/cimgui/cimgui.git --depth 1
	git -C cimgui submodule update --init --recursive --depth 1

CIMGUI=cimgui/libcimgui.a
$(CIMGUI): ; $(MAKE) -C cimgui static

main: $(CIMGUI) main.c ; gcc main.c $(CIMGUI) -lm -o $@

clean: ; rm -f main $(CIMGUI) ; $(MAKE) -C cimgui clean
```

``` c
// main.c
#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#include "cimgui/cimgui.h"
int main() { igCreateContext(NULL); }
```

Reading through (some of) the comments on https://github.com/ocornut/imgui/issues/1879, it seems some of the motivation for `cimgui` is to allow using Dear ImGui with a C compiler via static library. Is that not the case or I am I doing it wrong?

Thanks for a cool project!

**Comment by sonoro1234** [comment]
>  it seems some of the motivation for `cimgui` is to allow using Dear ImGui with a C compiler via static library.

main motivation is allow using Dear ImGui with a C compiler via dynamic library, because it is a dynamic library that has an ffi C interface easily accesed from another languages.

> /usr/bin/ld: imgui_demo.cpp:(.text+0x168e0): undefined reference to `__cxa_guard_acquire'
> /usr/bin/ld: imgui_demo.cpp:(.text+0x169b6): undefined reference to `__cxa_guard_release'

I have no experience with static cimgui compiling but I would say that this message implies that some library is missing in the linking phase (the library that provides `__cxa_guard_acquire').
Could it be the runtime library?

**Comment by steadysupply** [comment]
Thanks for the feedback `:)`

Sorry I don't use CMake! I found that the following patch

```patch
diff --git a/Makefile b/Makefile
index ca52247..90cc096 100644
--- a/Makefile
+++ b/Makefile
@@ -6,9 +6,10 @@ OBJS = cimgui.o
 OBJS += ./imgui/imgui.o
 OBJS += ./imgui/imgui_draw.o
 OBJS += ./imgui/imgui_demo.o
+OBJS += ./imgui/imgui_tables.o
 OBJS += ./imgui/imgui_widgets.o
 
-CXXFLAGS=-O2 -fno-exceptions -fno-rtti
+CXXFLAGS=-O2 -fno-exceptions -fno-rtti -fno-threadsafe-statics
 
 UNAME_S := $(shell uname -s)
 ```
lets me build a viable static library that compiles with C. I suppose I might be able to find some compile flags for GCC that give similar results, but I'm happy with the above patch for now ...

**Comment by kkukshtel** [comment]
@steadysupply Wondering if you're albe to help here —

I'm working with sokol and sokol_imgui and am trying to figure out how to compile sokol + sokol_imgui (sokol as a backend for imgui) + cimgui (sokol uses this) + dearimgui into a single DLL. However I'm getting what look like compiler errors in dear imgui, (stuff like "cant find symbol constexpr"), and am wondering what step I'm missing to make it happen. Any help would be much appreciated!
