### ISSUE TITLE
cimgui.h re-defines snprintf to sprintf_s on windows

### ISSUE THREAD

**Issue by Maurogik** [cimgui/cimgui#185]
I just found out that on Windows, snprintf redirects to sprintf_s. That's not a very good idea for a lot of reasons :

-  The two functions, while they take the same arguments, don't provide the same result (for example, the way I found out : _s versions will assert if the string is too long to be stored, instead of truncating it like snprintf does). The [doc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-s-sprintf-s-l-swprintf-s-swprintf-s-l?view=msvc-160) has more info in the "Remarks" section
- The snprintf macro is being leaked outside of cimgui.h (where it isn't actually being used). Meaning that snprintf was redirected to sprintf_s in the rest of my code, and that's plain wrong.

It looks like the define could be move to cimgui.cpp, or simplly deleted (it doesn't seem to be used in the cpp either).

**Comment by sonoro1234** [comment]
It comes from long long ago.
Just pushed commit to drop that.
