### ISSUE TITLE
Random crashes that are impossible to debug due to missing Exception throwing

### ISSUE THREAD

**Issue by julcreutz** [cimgui/cimgui#187]
I'm using ImGUI.NET (which uses cimgui) for an in-game editor for my game. Particles, Entities, Tiles, Maps etc.

Sadly, the game crashes randomly upon events in ImGUI. This can just be activating the editor, clicking something etc.

The game silently crashes, without an exception being thrown.

This is driving me nuts. Is there any way I could debug this?

The error code is always just a random number. Usually very large, sometimes it's 1.

This may be helpful: the windows crash log says something about "StackHash_a99c".

Hey, so I've analyzed a few crash dumps of mine and found something.

I'm not an expert, but I suppose the most notable lines are these right here:

```
cimgui!igValueInt+0x1f279

ntdll!RtlFreeHeap+0x51
```

I've appended the full crash dump analysis.

This is a repost from the ImGUI.NET repo, but I haven't received a helpful answer there yet.

[windbg_crashdump_analysis.txt](https://github.com/cimgui/cimgui/files/6365790/windbg_crashdump_analysis.txt)

**Comment by sonoro1234** [comment]
Exception throwing is set at compile time, see: https://github.com/cimgui/cimgui/pull/104
So you can recompile with exception handling.

But I dont think that exceptions are what you need, it would really help to recompile all in Debug mode and then you would get imgui assertions enabled (which often provide useful info)

Another very important thing is that cimgui.dll and ImGUI.NET generated binding are in sync (you should compile from the exact commit in cimgui that was used to do ImGUI.NET generation)

**Comment by julcreutz** [comment]
> Exception throwing is set at compile time, see: #104
> So you can recompile with exception handling.
> 
> But I dont think that exceptions are what you need, it would really help to recompile all in Debug mode and then you would get imgui assertions enabled (which often provide useful info)
> 
> Another very important thing is that cimgui.dll and ImGUI.NET generated binding are in sync (you should compile from the exact commit in cimgui that was used to do ImGUI.NET generation)

Gotcha, thanks so much for the quick help! I'm gonna get right to it. I'm not used to developing with C/C++, so this is a bit new to me.

**Comment by julcreutz** [comment]
> Exception throwing is set at compile time, see: #104
> So you can recompile with exception handling.
> 
> But I dont think that exceptions are what you need, it would really help to recompile all in Debug mode and then you would get imgui assertions enabled (which often provide useful info)
> 
> Another very important thing is that cimgui.dll and ImGUI.NET generated binding are in sync (you should compile from the exact commit in cimgui that was used to do ImGUI.NET generation)

Okay, so I got it compiling. I was on Ubuntu and decided to comment out the operating system cases other than Windows, so I get the .dll.

I was getting an error that limm32 was missing, so I commented that line out.

The resulting .dll gives me a BadImageException, which is probably due to limm32 missing?

**Comment by sonoro1234** [comment]
What makefile are you using?

**Comment by julcreutz** [comment]
> What makefile are you using?

The makefile included in the repository.

**Comment by sonoro1234** [comment]
You cant expect this repo to be in sync with ImGui.NET
You should build with ImGui.NET nativebuilds

**Comment by julcreutz** [comment]
> You cant expect this repo to be in sync with ImGui.NET
> You should build with ImGui.NET nativebuilds
> 
> https://github.com/mellinoe/imgui.net-nativebuild

Oh, I wasn't even aware of that repo. Sorry!

**Comment by julcreutz** [comment]
UPDATE: I got it compiling and now it's throwing errors when it crashes, which is amazing. Thanks again for the help!

**Comment by sonoro1234** [comment]
Closing now.
