### ISSUE TITLE
How to manipulate a `ImVector_`?

### ISSUE THREAD

**Issue by Gnimuc** [cimgui/cimgui#188]
For example, I need to do a `push_back` to `ImGuiPlatformIO`'s `Monitors` field which is an `ImVector_ImGuiViewportPtr`.

**Comment by sonoro1234** [comment]
As you have already seen this is related to #103. ImVector types are iterated easily for reading without changes in cimgui. But for doing push_back a C wrapping seems to be needed. There are two options: wrap manually the needed functions or undo commit https://github.com/cimgui/cimgui/commit/0f5aa16fe8abe0fb492535702c30a597cc358506 but disable those functions which are conflictive (as seen in https://github.com/ocornut/imgui/issues/2801). First alternative seems better if there are few functions needed.

**Comment by Gnimuc** [comment]
I've handled the use of `ImVector_XXX` types in a native Julia way.
