### ISSUE TITLE
Guard `igImFontAtlasGetBuilderForStbTruetype` behind a feature macro such as `IMGUI_ENABLE_STB_TRUETYPE`

### ISSUE THREAD

**Issue by ruifengx** [cimgui/cimgui#193]
As is described [here](https://github.com/imgui-rs/imgui-rs/pull/582#issuecomment-1001014540), with `freetype` and `docking` feature enabled, compiling `cimgui` for `imgui-rs` on Windows failed, and I managed to narrow the problem to the binding `igImFontAtlasGetBuilderForStbTruetype`.

Below is a quote from that linked pull request:

> The error mentions unresolved external symbol for `ImFontAtlasGetBuilderForStbTruetype`. After some investigations, it seems that this function is guarded by the macro `IMGUI_ENABLE_STB_TRUETYPE` in [`imgui_draw.cpp`](https://github.com/ocornut/imgui/blob/512c54bbc062c41c74f8a8bd8ff1fd6bebd1e6d0/imgui_draw.cpp#L2596-L2603). And according to [these lines](https://github.com/ocornut/imgui/blob/512c54bbc062c41c74f8a8bd8ff1fd6bebd1e6d0/imgui_internal.h#L104-L106), `IMGUI_ENABLE_STB_TRUETYPE` is only automatically defined if `IMGUI_ENABLE_FREETYPE` is not defined.
>
> So, in theory, `ImFontAtlasGetBuilderForStbTruetype` becomes undefined after enabling the `freetype` feature here, but in `cimgui`, the binding to `ImFontAtlasGetBuilderForStbTruetype` (named `igImFontAtlasGetBuilderForStbTruetype`) is [unconditional](https://github.com/cimgui/cimgui/blob/afce852875e36e948951d6253963cea46101c17c/cimgui.cpp#L4579). Therefore I would expect link errors occur on every platform, but I cannot even reproduce the errors on my PC... (Maybe some link mechanism is taking effect here.)

I am not entirely sure how each specific linker is designed to behave if one of the unresolved external symbols appear in one of the unused functions, but I recall that such a thing should be an undefined behaviour according to the C/C++/Rust standard. I can be 100% wrong about the specific mechanism, because I cannot even reproduce the link error on my local PC, but anyway, the aforementioned binding is indeed the cause of [the build failure](https://github.com/imgui-rs/imgui-rs/runs/4631776278?check_suite_focus=true), because by [removing the reference to `ImFontAtlasGetBuilderForStbTruetype`](https://github.com/ruifengx/imgui-rs/commit/572873bf5734d22624e84658a83a0bf6b80227e7#diff-a82895948ba19f1abd1006f02066150b9c6a206d14a2d017ec50ef68b3d52469), [compilation and linking passes](https://github.com/ruifengx/imgui-rs/runs/4631866086) as I expected.

**Comment by sonoro1234** [comment]
@ruifengx 
@ocornut
I did try a modification of generator.lua for adding the flag `IMGUI_ENABLE_FREETYPE` but the original problem seems to be that with `-DIMGUI_ENABLE_FREETYPE` in imgui compilation `ImFontAtlasGetBuilderForStbTruetype` is still present in imgui_internal.h:L3107 from which cimgui gets it

**Comment by ocornut** [comment]
Pushed the fix https://github.com/ocornut/imgui/commit/980deb4c9eaf0702e97be1309d9cd10aaf8467af

**Comment by sonoro1234** [comment]
Still missing docking branch?

**Comment by ocornut** [comment]
Merged to docking now.

**Comment by sonoro1234** [comment]
When 1.87 is published everything will be as told above

**Comment by sonoro1234** [comment]
Should be correct now

**Comment by Beefster09** [comment]
This seems to have regressed on 1.89.8dock

**Comment by sonoro1234** [comment]
@Beefster09 could you explain a bit?
