### ISSUE TITLE
Missing RenderWindowTitleBarContents

### ISSUE THREAD

**Issue by PAI5REECHO** [cimgui/cimgui#200]
I'd like to use some of the miscellaneous functions such as `RenderWindowTitleBarContents` but they're not exposed through `cimgui`

**Comment by sonoro1234** [comment]
Could you post a link to where is it found in imgui?

**Comment by PAI5REECHO** [comment]
I'm not sure if these should be considered part of the private API or not.
https://github.com/ocornut/imgui/blob/fa2b318dd6190852a6fe7ebc952b6551e93899e0/imgui.cpp#L969-L980
Maybe it's best to get the titlebar draw area as mentioned in https://github.com/ocornut/imgui/discussions/4865#discussioncomment-2133073

**Comment by sonoro1234** [comment]
cimgui only wraps those functions declared in imgui.h and imgui_internal.h so that `RenderWindowTitleBarContents ` being declared in imgui.cpp is not reachable.
