### ISSUE TITLE
`ImVec2ih_ImVec2ih_Vec2` has empty `ret`

### ISSUE THREAD

**Issue by oprypin** [cimgui/cimgui#205]
https://github.com/cimgui/cimgui/blob/08d5ad7f93eb169377c20bd42748877a41759b63/generator/output/definitions.json#L11270-L11289

https://github.com/cimgui/cimgui/blob/08d5ad7f93eb169377c20bd42748877a41759b63/generator/output/definitions.json#L11286

This is the only function that has `"ret": ""`. That seems to be invalid. This is new in https://github.com/cimgui/cimgui/commit/08d5ad7f93eb169377c20bd42748877a41759b63

**Comment by sonoro1234** [comment]
Thanks for catching this
