### ISSUE TITLE
backend usage

### ISSUE THREAD

**Issue by blackedout01** [cimgui/cimgui#206]
I don't understand how to compile a project using a custom backend. Am I supposed to modify the imgui source code?
I generated a "backend" for win32 and opengl3 but these are just the header files.
When I try to use them in my project I get unreferenced symbols to the functions defined in the C backend implementation.
Of course. Because these functions are compiled as C++ so the symbols don't match.
I read the open question issue but still don't understand and am just as confused as the guy that commented there. It's locked so I can't comment there unfortunately.
The examples don't really help me because they just include the cimgui header and then call functions that are defined in the backend. How is that supposed to work?
I must be missing something obvious so it would be really nice if someone could help me out. Thanks

**Comment by sonoro1234** [comment]
> When I try to use them in my project I get unreferenced symbols to the functions defined in the C backend implementation.

As told in https://github.com/cimgui/cimgui/issues/157 you should add `imgui_impl_win32.cpp` to cimgui compilation and thats all!!

If you look at https://github.com/cimgui/cimgui/blob/master/backend_test/example_sdl_opengl3/CMakeLists.txt on line 66 you will see that `imgui_impl_sdl.cpp` is added to the module compilation

**Comment by blackedout01** [comment]
Thanks for your response. I tend to avoid build tools where possible to keep the build process as simple as possible.
But I probably should have taken a look at that file. It sets IMGUI_IMPL_API to extern "C" which I didn't do because I thought this macro was for all imgui functions. But it makes sense now and after defining that macro it works.
