### ISSUE TITLE
Cannot compile latest commit with CMake

### ISSUE THREAD

**Issue by MarioGK** [cimgui/cimgui#208]
Hi i can compile older commits just fine with my [own](https://github.com/MarioGK/ImGuiSharp/blob/main/native/CMakeLists.txt) CMake file, [LuaJit](https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/CMakeLists.txt)'s CMake file as well, but as soon as i update the submodules running `git submodule update --recursive --remote` it stops compiling giving errors like:
`missing type specifier - int assumed`
`syntax error: missing ';' before '*'`
`syntax error: identifier 'ImGuiDockNodeFlags'`

I tried using Visual Studio and Mingw-WinBuilds and they give the same errors.

**Comment by sonoro1234** [comment]
Branch?
Compile error info with line and file?

**Comment by MarioGK** [comment]
> Branch? Compile error info with line and file?

Hi, sorry for missing information, the branch i used is master.
To recreate this you can clone https://github.com/sonoro1234/LuaJIT-ImGui
Run `git submodule update --recursive --remote`
Then `cmake .`
Then `cmake --build . --config Release`

[Full error log](https://hastebin.com/ajocubekig.apache)

**Comment by sonoro1234** [comment]
I am not getting errors building cimgui nor building LuaJIT-ImGui docking-inter branch.(The default branch)

Are you trying to build LuaJIT-ImGui master branch'

**Comment by MarioGK** [comment]
I am using LuaJIT-ImGui docking-inter branch with cimgui master branch.
I ran the commands that i send above and i get those errors.

**Comment by sonoro1234** [comment]
LuaJIT-ImGui was not updated.
Could you try again?

**Comment by MarioGK** [comment]
```git clone --recurse-submodules https://github.com/sonoro1234/LuaJIT-ImGui.git
cd LuaJIT-ImGui
git submodule update --recursive --remote
cmake .
cmake --build . --config Release```
I ran these exact commands and i still get error while compiling, if i skip ```git submodule update --recursive --remote``` this line it compiles just fine.

**Comment by sonoro1234** [comment]
First: Would be a LuaJIT-ImGui issue and not a cimgui one.
Second: I am not a git expert, so I cant tell you why your  `git submodule update --recursive --remote` is failing. What I know is that it is not necessary if you clone with `git clone --recurse-submodules https://github.com/sonoro1234/LuaJIT-ImGui.git`.
In case the repo is already cloned and you just want to update submodules the command recomended is `git submodule update --init --recursive` (without --remote)

**Comment by MarioGK** [comment]
It is not a lua jit problem and it is not a git problem you got the problem wrong.
```
git submodule update --recursive --remote
```
This command only update the submodule in this case cimgui to the latest commit.
So the problem is that the latest commit of cimgui doesn't compile and earlier versions of cimgui does, it is not related to git or luajit at all.

**Comment by sonoro1234** [comment]
It is a LuaJIT-ImGui issue if you try to compile LuaJIT-ImGui. 
But the problem happens also while building cimgui:

If you use `remote` in sulbmodule update, the imgui submodule goes to its last commit (which should not be: "Fix ImGuiIO docs and default values"), but if you use `--init --recursive` the imgui submodule goes to the correct imgui commit ("Merge branch 'master' into docking") referenced from cimgui. (You can check it from github web interface by clicking on imgui submodule from cimgui repo)

From https://git-scm.com/docs/git-submodule:
```
This option is only valid for the update command. Instead of using the superproject’s recorded SHA-1 to update the submodule, use the status of the submodule’s remote-tracking branch.
```
