### ISSUE TITLE
Is it possible to generate convinient function which omits all the args with default value?

### ISSUE THREAD

**Issue by AllenDang** [cimgui/cimgui#216]
I'm creating a binding for golang. Golang is a language lacks of default arg like C does, so I'm thinking about to generate a `convinient` version for all the functions which have default args.

For example
```c
CIMGUI_API bool igDragInt(const char* label,int* v,float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
```
```c++
IMGUI_API bool DragInt(const char* label, int* v, float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char* format = "%d", ImGuiSliderFlags flags = 0)
```

Most of the time, if user doesn't need to set all the args, he could pass only 2 args.

Is it possible to generate `convinient` and `full` versions for DragInt like:
```c
// Convinient version
CIMGUI_API bool igDragInt(const char* label,int* v);

// Full version with V suffix
CIMGUI_API bool igDragIntV(const char* label,int* v,float v_speed,int v_min,int v_max,const char* format,ImGuiSliderFlags flags);
```

**Comment by sonoro1234** [comment]
> Golang is a language lacks of default arg like C does

C does not allow default args.
Defaults could be handled in Go as it is done in LuaJIT-ImGui https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/lua/imgui/glfw.lua#L5503
If value is nil give arg the default value

**Comment by AllenDang** [comment]
I know C does not allow default args, my meaning is generate two functions, and the convinient one calls the full version with default args.

```c
bool igDragInt(const char* label,int* v) {
  return igDragIntV(label, v, 1.0f, 0, 0, "%d", 0);
}
```

**Comment by sonoro1234** [comment]
What prevents doing that from Go as done in LuaJIT-ImGui?

**Comment by AllenDang** [comment]
Go deosn't support to omit an arg and make it as nil (lua supports that). 
If a function has 6 args, user has to pass 6 args, no more no less, and nil could not be passed to any type like lua did.

**Comment by sonoro1234** [comment]
But you could create the convinient function in Go which calls the full function in C?

**Comment by AllenDang** [comment]
@sonoro1234 Yes, I could do that. I just think this work might need to be done for every wrapper in other languages, so I'm here to ask if it's possible to do it in the root.

**Comment by sonoro1234** [comment]
> might need to be done for every wrapper in other languages

Not to my knowledge

**Comment by AllenDang** [comment]
Ok, I'll do it on Go side. Thanks.
