### ISSUE TITLE
Are hardware cursors supported?

### ISSUE THREAD

**Issue by aybe** [cimgui/cimgui#218]
I am using your library through ImGui.NET and OpenTK. currently, only an arrow cursor is shown.

Trying to pinpoint what's causing this, can you confirm that cimgui actually supports mouse cursors?

Thank you.

**Comment by sonoro1234** [comment]
Handled in imgui backends. But imgui.Net has its own backend

**Comment by aybe** [comment]
Alright, thank you.

**Comment by sonoro1234** [comment]
It would be useful to replicate main.cpp example from imgui repo using imgui backends

**Comment by aybe** [comment]
Thank you, that turned out to be really helpful!

[Here's the solution](https://github.com/ocornut/imgui/issues/5739#issuecomment-1268734162) for those having the same issue.
