### ISSUE TITLE
[docs] Suggestion regarding "getting started" guide (using "backend_test" example)

### ISSUE THREAD

**Issue by drk-mtr** [cimgui/cimgui#222]
Thanks for the brilliant library! This is just a small suggestion for the documentation. 

I'm a beginner, so when I found this library I didn't know how to get started. I know it will be obvious to everyone else, but in some other languages you install libraries using a package manager, so I didn't even know whether I needed to compile it. Would there be any value in adding some step-by-step instructions to help minimise queries? E.g.

## getting started

To get started with a minimal C application, you can use the examples in the `backend_test` folder. The following steps apply for Debian, but similar principles apply elsewhere.

```bash
# Clone this repository
git clone --recursive https://github.com/cimgui/cimgui.git

# Open one of the `backend_test` folders e.g. `example_sdl_opengl3`
cd cimgui/backend_test/example_sdl_opengl3/

# Make sure the relevant backend is installed - in this case SDL2
sudo apt install libsdl2-dev

# Check whether CMake is installed
# It can be installed here if not: https://cmake.org/install/
cmake --version

# Run CMake to create the files necessary to build the application
cmake -S ./ -B ./build

# Open the `./build` folder that should get created
cd build/

# Run `make` to build the executable
make

# Run the executable
./test_sdl
```

Sorry if this is a bad suggestion, I've only just started using C so I appreciate it might be too basic or specific to my environment.

**Comment by sonoro1234** [comment]
> Would there be any value in adding some step-by-step instructions to help minimise queries?

Yes, of course. Where should this be added? Perhaps as a pinned issue? Wiki?

**Comment by drk-mtr** [comment]
Thanks! I'd say the wiki is probably best as that's the first place people will land.

**Comment by sonoro1234** [comment]
I think anyone can edit the wiki, so feel free to add this content as a wiki page.

**Comment by drk-mtr** [comment]
Thanks very much! I've just submitted a PR but on re-reading this thread I'm not 100% sure I've understood correctly - did you mean the README.md is the correct place for this?

**Comment by sonoro1234** [comment]
> Thanks! I'd say the wiki is probably best as that's the first place people will land.

That is what you said!!

**Comment by drk-mtr** [comment]
If wiki = readme then we agree ha - thanks again
