### ISSUE TITLE
Will 'master' branch be updated?

### ISSUE THREAD

**Issue by oprypin** [cimgui/cimgui#225]
Hi!
I've been relying on 'master' branch because:
* It is based on the officially released code of *imgui*
* It has all the pre-generated JSON that I need
* It pins a repository with imgui as well, which I also need and I've been directly using that subrepo

Now it seems that the 'master' branch hasn't been updated in a while in *cimgui*, so only the 'docking' branch is available.

I understand that I can probably just manage the version pin myself and also run the generator myself.

But before I resort to that, I figured I'd ask whether the 'master' branch is really discontinued.

**Comment by sonoro1234** [comment]
I will do the merge commit tomorrow

**Comment by oprypin** [comment]
Thanks much for your work!

I don't know whether to close this 🙂

**Comment by sonoro1234** [comment]
Just done. 
But it does not seem a merge commit!!  Something got broken in a previous commit.  I expect it is all correct now.

**Comment by oprypin** [comment]
Sorry, would you consider updating the branch? `master` is at 1.89.3, compared to 1.89.5 in `docking_inter`

**Comment by zaafar** [comment]
@oprypin  docking_inter is actually 1.89.4 :p

**Comment by sonoro1234** [comment]
done both branches
