### ISSUE TITLE
Feature request: Allow disabling parts of wrapper library

### ISSUE THREAD

**Issue by shinymerlyn** [cimgui/cimgui#228]
I would like the generated header and implementation to support preprocessor flags to disable unused parts of Dear ImGui. For example the demo window functions, though maybe there's other pieces that would make sense too.

I'm building a statically linked zig + GLFW + OpenGL 3 + Dear ImGui binary. I would like my executable to be as small as I can get it without having to do crazy things. The starting size was 1209kb. Getting rid of `imgui_demo.cpp` and all related functions (and commenting them out in cimgui) brings it down to 998kb, which seems worth doing in apps that aren't using those functions.

Dear ImGui itself would ideally be able to disable those defines as well, but that's sort of a different issue. Dear ImGui itself doesn't need to change for me to get the reduction in binary size. I just have to not link `imgui_demo.cpp`. Currently it is only cimgui that ends up needing to have code commented out in order to make that possible. So I think it isn't strictly an upstream issue.

**Comment by sonoro1234** [comment]
Done in https://github.com/cimgui/cimgui/blob/docking_inter/generator/generator.lua#L78

**Comment by sonoro1234** [comment]
Done
