### ISSUE TITLE
Typedef generation issue

### ISSUE THREAD

**Issue by anddam** [cimgui/cimgui#231]
Are [this definition](https://github.com/cimgui/cimgui/blob/docking_inter/generator/output/typedefs_dict.json#L2) and the corresponding Lua one correct for a C API considering how it's been translated [here](https://github.com/cimgui/cimgui/blob/2c8eab86f7ba7ea2b1076a23cb730fed8d8e2b2b/cimgui.h#L1855)?

**Comment by sonoro1234** [comment]
One is the C++ version, the other the C version

**Comment by anddam** [comment]
Then it makes sense. I hit this while trying to update nimgl/imgui —that wraps cimgui— and the function template popped out in nim generated code, that seemed odd (to me) since it was wrapping the C library. I haven't delved into the generator, will move the discussion there.
Thanks
