### ISSUE TITLE
can't make it use ImWchar32

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimgui#232]
Hi
I generated binding with `./generate.sh -DIMGUI_USE_WHCAR32` (like readme says)
but it still seems to use ImWchar16...
```header
typedef ImWchar16 ImWchar;
```

what am I doing wrong? Or probably I missunderstood how USE_IMGUI_WHCAR32 works?

**Comment by sonoro1234** [comment]
You must edit generator.sh to add -DIMGUI_USE_WCHAR32

**Comment by gucio321** [comment]
hmm, I see. Maybe there is a way to include command-line arguments in this script?

**Comment by gucio321** [comment]
maybe a quick edit like this? I can create a PR, but let me know if you want this change :smile:
```diff
diff --git a/generator/generator.sh b/generator/generator.sh
index 92d7ae4..e2840c5 100755
--- a/generator/generator.sh
+++ b/generator/generator.sh
@@ -22,4 +22,4 @@ then
   suffix='.exe'
 fi
 
-luajit$suffix ./generator.lua gcc "internal noimstrv" glfw opengl3 opengl2 sdl2
+luajit$suffix ./generator.lua gcc "internal noimstrv" glfw opengl3 opengl2 sdl2 "$@"
```

**Comment by gucio321** [comment]
hmm, I see what... maybe introduce some flags-parser logic in generator.sh?
e.g. `./generator.sh --cflags="-DIMGUI_USE_WCHAR32"`?
The point is that using generator in some automatic jobs becomes a bit difficult as long as I need to edit it...

**Comment by sonoro1234** [comment]
the best would be for you to have your own generator.bat (sh) outside cimgui repo edited as:

```
cd cimgui/generator
luajit ./generator.lua gcc "internal noimstrv" glfw opengl3 opengl2 sdl2 -DIMGUI_USE_WCHAR32
```

**Comment by gucio321** [comment]
> the best would be for you to have your own generator.bat (sh) outside cimgui repo edited as:
> 
> ```
> cd cimgui/generator
> luajit ./generator.lua gcc "internal noimstrv" glfw opengl3 opengl2 sdl2 -DIMGUI_USE_WCHAR32
> ```
> 
> That way you are able to update cimgui but keeping your generator options

I've considered it, however, note that the current generator.sh already contains more stuff than just luajit call...
I'd rather raly on upstream as long as possible. Let me know what do you think about the solution mentioned above and I can edit my PR.

**Comment by sonoro1234** [comment]
> I'd rather raly on upstream as long as possible.

Yes, but upstream cimgui has some predefined options hardcoded in generator.bat. The only way to have your own options is having your own generator.sh outside cimgui changing this line:

```
cd cimgui/generator
luajit$suffix ./generator.lua gcc "internal noimstrv" glfw opengl3 opengl2 sdl2 -DIMGUI_USE_WCHAR3
```

**Comment by gucio321** [comment]
I see, I'm just wondering why not add `--cflags` script flag to `generator.sh`? Currently hard-coded options may be left as are, or even better could be stored as defaults in some overwritable flag.
And I'll be able to do `./generator.sh --cflags="-DIMGUI_USE_WCHAR32"`

**Comment by sonoro1234** [comment]
Perhaps update your PR so that I can understand how would it be?
