### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by fedesape21** [cimgui/cimgui#236]
hi, 

i have an issue when I try to run make, I can't figure out how to fix it.

`4 warnings generated.
[100%] Linking C executable test_sdl
Undefined symbols for architecture arm64:
  "_glClear", referenced from:
      _main in main.c.o
  "_glClearColor", referenced from:
      _main in main.c.o
  "_glGetString", referenced from:
      _main in main.c.o
  "_glViewport", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test_sdl] Error 1
make[1]: *** [CMakeFiles/test_sdl.dir/all] Error 2`

<img width="1440" alt="Captura de pantalla 2023-04-08 a la(s) 22 22 57" src="https://user-images.githubusercontent.com/64945792/230749506-2da20a58-c604-4279-9c3d-7b0e2fb55412.png">

**Comment by sonoro1234** [comment]
Failing opengl symbols on arm64 macosx
I cant test as I dont have macosx.
Google?

**Comment by sonoro1234** [comment]
framework OpenGL should be added?
Could you compile imgui sdl opengl example?

**Comment by fedesape21** [comment]
Thank you for your answer,

at first can't link because of -lgl, but I changed it for -OpenGL and linked well

I tried with `-framework OpenGL` on `target_link_libraries`

but tells me 

`Cannot find source file:
-framework OpenGL`

**Comment by fedesape21** [comment]
nop, I can't

<img width="942" alt="Captura de pantalla 2023-04-09 a la(s) 17 51 57" src="https://user-images.githubusercontent.com/64945792/230796010-2d45e24b-a32e-4bb3-ab81-ef1bdfb17d19.png">

**Comment by sonoro1234** [comment]
> at first can't link because of -lgl, but I changed it for -OpenGL and linked well

Compiling which program?

**Comment by sonoro1234** [comment]
https://github.com/ocornut/imgui/tree/master/examples/example_sdl2_opengl3

Or

https://github.com/cimgui/cimgui/tree/docking_inter/backend_test/example_sdl_opengl3
