### ISSUE TITLE
VSCode Issue?

### ISSUE THREAD

**Issue by Mezo-hx** [cimgui/cimgui#237]
Didn't really know anyone to ask for help so uh, here I am.

Issue:
[Issue.txt](https://github.com/cimgui/cimgui/files/11225765/Issue.txt)

Makefile:

```
include config.mk

SRC = $(shell find -name "*.c")
OBJ = ${SRC:.c=.o}
DEP = ${SRC:.c=.d}

celLinux.so: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS}

-include ${DEP}

.c.o:
	$(CC) -MM -MT $@ -MF $(patsubst %.o, %.d, $@) ${CFLAGS} $<
	${CC} -o $@ -c ${CFLAGS} $<

${OBJ}: config.mk Makefile

clean:
	rm -f celLinux.so ${OBJ} ${DEP}

.PHONY: clean
```

config.mk:

```
INCLUDE_DIR = ext/cimgui
INCLUDE_DIR2 = ext/cimgui/generator/output
INCLUDE_DIR3 = ext/gl3w/GL
INCLUDE_DIR4 = ext/linmath

LIBS = -lpthread -lcjson -lGLEW -lSDL2 -lcimgui -lcimgui_impl -llinmath -lgl3w

CPPFLAGS = -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -I$(INCLUDE_DIR) -I$(INCLUDE_DIR2) -I$(INCLUDE_DIR3) -I$(INCLUDE_DIR4)
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Wno-pointer-arith -O2 -fPIC ${CPPFLAGS}
LDFLAGS  = -shared
CC = gcc
```

the code I used was from this repo file: https://github.com/peko/cimgui-c-example/blob/master/src/main.c

**Comment by sonoro1234** [comment]
https://github.com/cimgui/cimgui/tree/docking_inter/backend_test/example_glfw_opengl3

**Comment by FacilitatedIsTaken** [comment]
> https://github.com/cimgui/cimgui/tree/docking_inter/backend_test/example_glfw_opengl3

I'm still having the undefined reference issue

```
/usr/bin/ld: Main.c:(.text+0x312): undefined reference to `igGetIO'
/usr/bin/ld: Main.c:(.text+0x32c): undefined reference to `igGetIO'
/usr/bin/ld: Main.c:(.text+0x36b): undefined reference to `igText'
/usr/bin/ld: Main.c:(.text+0x370): undefined reference to `igEnd'
etc . . .
```

**Comment by sonoro1234** [comment]
> For CMake, I copied the code from the github repo you sent, and modified some of the include directories

The github repo I sent is THIS github repo, which is the one you should try to build:
Without modifiying anything in the repo and from any folder used to build youl should type

```
cmake "path to cimgui"/backend_test/example_glfw_opengl3

make
```

In case you have several compilers you should also add a cmake option for choosing compiler. For example `-G"Unix Makefiles"` as found in https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#manual:cmake-generators(7)

In case of errors post the command-line response
