### ISSUE TITLE
imgui 1.89.6 is out cimgui is on 1.89.5

### ISSUE THREAD

**Issue by zaafar** [cimgui/cimgui#242]
Thanks for maintaining such an awesome project.
Nothing urgent or anything, just an FYI.

**Comment by sonoro1234** [comment]
seems spurious fail in windows not founding LuaJIT
1.89.6 done.

**Comment by sonoro1234** [comment]
It is not a spurious fail. Try to solve in last commit but no success. Perhaps @rokups can take a look as my github actions skills are zero.
