### ISSUE TITLE
There is no CIMGUI_USE_VULKAN in the provided cimgui_impl.h file

### ISSUE THREAD

**Issue by theanimatorspal** [cimgui/cimgui#244]
I am trying to compile cimgui_sdl_vk, but there is no CIMGUI_USE_VULKAN, so some of the things are missing.

Precisely static void ```ImGui_ImplVulkanH_Window``` is Missing while building.

**Comment by sonoro1234** [comment]
You need to perform generation with vulkan option enabled

**Comment by theanimatorspal** [comment]
That means, Vulkan with SDL is not already generated? 😢 I request adding them.

**Comment by sonoro1234** [comment]
It needs vulkan sdk as a dependency
