### ISSUE TITLE
Coherent content for generated files

### ISSUE THREAD

**Issue by tiawl** [cimgui/cimgui#245]
Hi,

I am trying to write a Zig binding generator with your generator because the current state of the art does not satisfy my needs for the mentioned programming language. I do not want that the final user call your generator directly because I do not want to manage platform specification for external processes from my binding during Zig compilation. So I use your generator (for a set of preselected potential usage) in my local clone and I push the generated content to the remote. Working this way, the final user will only need:
- a C compiler,
- the Zig programming language,
- your repository,
-  the generated content matching its usage

when compiling its app. No `luajit` dependency and no need to have a shell to run your generator.

However I did not expect that JSON and Lua generated files will be different. Currently Zig is a young programming language and can only parse JSON files. So I can only rely on the JSON part of your generated file to generate the binding during the Zig compilation. But I missing some data. Would you consider to add a flag to your `generator.sh` script allowing to skip this part of your `generator.lua` ?

```lua
--delete extra info for json
structs_and_enums_table.templated_structs = nil
structs_and_enums_table.typenames = nil
structs_and_enums_table.templates_done = nil
```

This will add coherence between different formats you use as output.
Thank you.

**Comment by sonoro1234** [comment]
done in last commit: no flag but always keeping extra info in JSON

**Comment by tiawl** [comment]
Great job, thank you for this !
