### ISSUE TITLE
Improve pointers specification

### ISSUE THREAD

**Issue by tiawl** [cimgui/cimgui#246]
Hi,

I am opening this issue to request new generated content. As mentioned in #245, I am working on a Zig binding generator.

Zig provides two ways to deal with C pointers (see here if interested: https://ziglang.org/documentation/master/#Pointers), and an optional type which allows programmers to deal with the C `null` value (see here if interested: https://ziglang.org/documentation/master/#Optional-Pointers).

Currently because I miss some data from your generated files, dealing with C pointers are making all my Zig pointers looking like this:
```zig
// if you did not follow the 2 links above you have to read it like this:
// my_pointer is an optional many-item pointer of my_type and is currently null
my_pointer: ?[*] my_type = null;
```

And that's it: the binding I am working can the do the job with this specification. However I am not totally satisfied with this: if Zig provides this level of detail when working with pointers, this is to allow programmers to make better specifications and avoid them to deal with unexpected failure cases.

For example, working with this C function: `ImBitVector_Create (ImBitVector* self, int sz)`
I think that representing the `self` parameter by an optional many-pointer of `ImBitVector` is a black point in my specification.
The mentioned function is supposed to fail if, for `self` I am providing:
- a `null` value,
- a pointer  to more than 1 `ImBitVector`.

So, for my users, instead of this Zig specification:
```zig
myZigBinding_ImBitVector_Create (self: ?[*] ImBitVector, sz: c_int)
```
it is better for them to work with this Zig specification:
```zig
myZigBinding_ImBitVector_Create (self: *ImBitVector, sz: c_int)
```

I know this repository is only providing a tool to generate content based on the ocornut/imgui repository. So I know it is not your job to provide this kind of specification for each pointer in each function/structure. But this is a collaborating feature with the mentioned repository and before opening an issue in it, I would like to know:
- are you OK to change your scripts to parse this kind of data if the ocurnut/imgui maintainer(s) is OK to provide this specification ?
- if you are OK but it is too much work from your side, will you accept a pull request to make these modifications ?
- if you are OK, what kind of data your scripts will expect to easily parse it ? (extra comments in the body of the function/struct ? on top of the function/struct ? into the prototype of the function/struct ? into a separated file with a specific format ? ...)

I do not expect you to accept this proposal because it is not a small change and the Zig binding generator I am working on will work even if you refuse. But if you accept it, it could really improve bindings' quality relying on your generator. I am talking about Zig here but there are many more programing languages that offers an optional type and a distinction between single and many pointers (Rust, Nim, Swift, F#, ...). Existing or future bindings from these programing languages will also take advantage of the arrival of this new data.

As a suggestion, you can look at the [Vulkan specification XML file](https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml) which provides this kind of specification for pointers (see `VkBaseOutStructure` for optional single-item pointers and `VkDeviceQueueCreateInfo` for many-item pointers).

Thank you.

**Comment by sonoro1234** [comment]
It depends on how is it handled in imgui. In C and C++ there is `*P` and `P[]` which would be the most sensible way to handle it?

**Comment by sonoro1234** [comment]
Yes

**Comment by tiawl** [comment]
I do not think it is a reliable way to distinguish between them:
- `*P` is a pointer annotation,
- `P[]` is an array annotation,

Even if when used as function parameter there is no difference I think it will confuse ocornut/imgui direct users.
In addition, this type of annotation does not work in a struct:
```c
#include<stdio.h>

// this program compiles successfully when using this struct definition:
struct test { int* mem; };
// but does not when you use this one instead:
struct test { int[] mem; };

void main (void)
{
  printf ("Hello World\n");
}
```
and we need to make distinction into a struct for pointer members.

And even if this solution could work, how do we distinguish between a pointer that can be `null` and a pointer that can not ?

**Comment by sonoro1234** [comment]
It is only for function args.
For struct definition you must specify lenght because memory is allocated `struct test { int mem[12]; };`

> And even if this solution could work, how do we distinguish between a pointer that can be `null` and a pointer that can not ?

There is no way for that in C or C++
We should first check in imgui when null is accepted as pointer argument (Is there any place?)

**Comment by tiawl** [comment]
I agree with you. You are highlighting the real points:
1) we can not rely on `*P`/`P[]` to make a distinction between single-item pointers and many-item pointers because:
> For struct definition you must specify length because memory is allocated
2) there is no way in C or C++ to distinguish between a pointer that can be `null` and a pointer that can not.

So we need to think about another way to specify it. This is what I am asking here:
> what kind of data your scripts will expect to easily parse it ? (extra comments in the body of the function/struct ? on top of the function/struct ? into the prototype of the function/struct ? into a separated file with a specific format ? ...)

I have the feeling that you do not understand my request. Maybe I have some trouble expressing it, so I am going to use other words:

My real intent is to make an ocornut/imgui issue showing that:
- you are OK to modify your generator to parse and expose more pointers data to your users **ONLY IF**:
  -  ocornut/imgui maintainer(s) are ready to expose a specification about this kind of data,
  -  you really want to (currently I do not know if you agree to modify your generator to parse and generate extra data),
- you expressed explicitly what kind of changes in ocornut/imgui repository could ease your job to parse and expose more pointers data.

Is it clearer ?

**Comment by tiawl** [comment]
I do not want to make an ocornut/imgui issue asking for a specification:
- if you do not want to parse it,
- without knowing what kind of modification can help you and ease your job if you are OK to parse it.

**Comment by sonoro1234** [comment]
I dont want to take this path unless it is really necessary.

Lets focus on real and specific problems: for ImBitVector_Create  which is a funtion * vs [] is enough and in this case null cant be used.

Which other specific issues are happening?

**Comment by sonoro1234** [comment]
I have the impression that in imgui code, everytime a pointer cant be null there is an assertion to check it, so that if the user uses NULL pointer he will get an assertion message.

**Comment by tiawl** [comment]
It is not a good practice to be blindly confident about code written by others. And even if you are right (and you probably are):
- why is it avoiding ocornut/imgui maintainer(s) to write a specification about this ?
- why is it avoiding my users to access a specification matching as mush as possible to the ocornut/imgui specification ?

**Comment by sonoro1234** [comment]
> * why is it avoiding ocornut/imgui maintainer(s) to write a specification about this ?

When did it happen?

**Comment by tiawl** [comment]
It did not. But this is the point of this issue: because it could improve bindings quality relying on your generator and because it could allow an explicit structured document writing about the Imgui API, I was expecting you to support this feature if I am requesting it to the ocornut/imgui repository. But you are surprisingly against. I do not understand why. I offer you my help and some points of reflection to ease your job and the ocornut/imgui maintainer(s) job but it does not seem you are not interested in. Did I miss something ?

**Comment by sonoro1234** [comment]
No, I am not personally interested in it because what is already done is enough for my use cases. I never found any problem with pointers in LuaJIT-ImGui. But I could perhaps help with it if we found a plan. Specifically omar should be interested in this plan.

**Comment by tiawl** [comment]
Ok, thank you for this discussion. I am going to open an issue to the ocornut/imgui linking to this one. I close this issue and I will open a new one here if the ocornut/imgui maintainer(s) are interested in (and if this results on potential changes on your generator).
