### ISSUE TITLE
Continued updates of master branch

### ISSUE THREAD

**Issue by oprypin** [cimgui/cimgui#250]
* From #225

Hi!
I am still totally reliant on the 'master' branch being updated to be able to update https://github.com/oprypin/crystal-imgui

I have actually developed a script that performs merge commits (like you've been doing) totally automatically and reliably, and I can unblock myself by pushing the merge commits to my fork. But still,

* Would you be interested in putting the script into this repo?
* Would you be interested in running the script yourself, if it's helpful?

Otherwise:

* Should I try to fully automate this with GitHub Actions (note that unfortunately it will require messing with "personal access tokens")
* Or should I just open pull requests to your master branch whenever I perform an update myself? :)

---

**This is the script:**
https://gist.github.com/oprypin/33d8b71f93bc60d8077e036e02939779

And this is how I ran the script to produce these merges:
https://github.com/oprypin/cimgui/commits/2e79a491949e1089be270aac25dd39a3328562e9

```bash
git fetch origin --tags
git checkout master
./merge_branch.sh 1.89.6dock
./merge_branch.sh 1.89.7dock
./merge_branch.sh 1.89.8dock
./merge_branch.sh 1.89.9dock
git push
```
but the argument is optional, otherwise it will just merge `docking_inter`, not a particular tag.

**Comment by sonoro1234** [comment]
Just updated master branch. 
Thank you for the script but I have to adapt it to Windows cmd and there are some things I still dont understand completely.
I need to study it a bit more!!

**Comment by oprypin** [comment]
Oh don't adapt it to cmd, just run Bash instead.

**Comment by oprypin** [comment]
Sorry but my questions remain unanswered. I don't know what your policy is for this situation - does this mean that I would need to keep opening an issue after each update and then you'll update the branch, or how to continue in the future?

**Comment by sonoro1234** [comment]
Until I can get to understand correctly your script I will try to remember merging docking_inter branch into master for every new tag. In case I forget, a PR will be welcomed.

**Comment by zaafar** [comment]
The script is basically doing the following.

1: merge docking branch into master
2: run generator.sh

I don't see the purpose or use of this script.

I think what he is trying to ask/say is "Please do not forget to keep master up to date".

**Comment by zaafar** [comment]
> I am still totally reliant on the 'master' branch being updated to be able to update https://github.com/oprypin/crystal-imgui


I think the real question is why is he still using master branch when everyone else is using docking branch. Why don't they move to docking_inter branch.

**Comment by oprypin** [comment]
If updating the branch is an annoying process
(I don't know how @sonoro1234 is doing it, and I'm sure it is not trivial at all)

And if that's the reason that the branch does not get regularly updated:
 
I am offering a script that turns it all into 1 action, or 0 actions if you are willing to look into automation solutions on GitHub, which I can contribute too.
