### ISSUE TITLE
how to use cimgui to wrap imgui_impl_sdl2, imgui_impl_sdlrenderer2 ?

### ISSUE THREAD

**Issue by hw-claudio** [cimgui/cimgui#258]
Hi I am trying to use imgui, but my code is all C which I prefer due to compilation times (and no real need for C++ features).

I found this cimgui project, and I am able to compile in the code using the pre-generated assets from the builds
(cimgui.json, cimgui.h, cimgui.cpp).

Since I am using SDL2 and SDL2 render API, I am also interested in the SDL2 backends,
is there some cimgui_sdl2.h, cimgui_sdl2_renderer.h I can use so as to leverage the existing SDL2 code in cimgui?

I found this Issue that I did not really understand:

https://github.com/cimgui/cimgui/issues/157

And I found also a reference to some LUA stuff as:

https://github.com/sonoro1234/LuaJIT-ImGui

but I am not interested in LUA, I just would like to have functions to call from C code in order to render the cimgui using SDL2 and SDL2 renderer.

Thanks for any hint!

**Comment by hw-claudio** [comment]
btw I got it done by manually changing imgui_impl_sdl2.h and imgui_impl_sdlrenderer2.h with:

--- a/imgui/imgui_impl_sdl2.h
+++ b/imgui/imgui_impl_sdl2.h
@@ -19,25 +19,25 @@
 // - Introduction, links and more at the top of imgui.cpp
 
 #pragma once
-#include "imgui.h"      // IMGUI_IMPL_API
-#ifndef IMGUI_DISABLE
+#ifdef __cplusplus
+extern "C"
+{
+#endif /* __cplusplus */

and adjusted a few more things here and there and it works.
I think it would be good though to leave the original files as they are and provide a cimgui_impl_sdl2.h and a cimgui_impl_sdl2renderer2.h automatically generated like is already done with cimgui.h

**Comment by 0Alastair1** [comment]
ImGui_ImplDX9 need bindings.
