### ISSUE TITLE
ImDrawCallback_ResetRenderState define is not exposed in cimgui.h

### ISSUE THREAD

**Issue by floooh** [cimgui/cimgui#261]
Just stumbled over this, not sure if it is by design (because it's a preprocessor define), but the cimgui.h header doesn't seem to expose the `ImDrawCallback_ResetRenderState` define:

https://github.com/ocornut/imgui/blob/277ae93c41314ba5f4c7444f37c4319cdf07e8cf/imgui.h#L2583-L2587

I can easily workaround this of course, just wanted to make you aware of it. If it is a "won't fix" feel free to close the issue of course :)

**Comment by sonoro1234** [comment]
done in https://github.com/cimgui/cimgui/commit/eb0649acf3a37d0d072d6b76fa51f9d851a04f33

**Comment by floooh** [comment]
Thanks! :)
