### ISSUE TITLE
Differences in structs between imgui_internal.h and cimgui.h

### ISSUE THREAD

**Issue by mondegreengames** [cimgui/cimgui#263]
It seems like cimgui.h was generated with `IMGUI_DISABLE_OBSOLETE_KEYIO` defined, but imgui_internal.h still thinks it is not defined. So the struct definitions disagree, which was causing weird bugs. For example, cimgui.h doesn't have the `KeyMap`, `KeysDown`, and `NavInputs` fields in the `ImGuiIO` struct, but imgui_internal.h does (at least out of the box), so if I try to access any fields defined after those missing fields I'm actually accessing memory that doesn't have valid values.

What is the best way to make sure the definitions agree? Should I globally define `IMGUI_DISABLE_OBSOLETE_KEYIO`?

**Comment by sonoro1234** [comment]
looking at imgui_internal.h I am not able to see any `KeyMap`

**Comment by mondegreengames** [comment]
Sorry about that. It's in imgui.h, in the ImGuiIO definition. https://github.com/ocornut/imgui/blob/868facff9ded2d61425c67deeba354eb24275bd1/imgui.h#L2196

**Comment by sonoro1234** [comment]
IMGUI_DISABLE_OBSOLETE_KEYIO is defined when (IMGUI_DISABLE_OBSOLETE_FUNCTIONS) is defined and this is used in standard cimgui generation and so should be used in compilation

**Comment by zaafar** [comment]
Feels like imgui issue….you might wanna report to them if this is still happening.

**Comment by mondegreengames** [comment]
> IMGUI_DISABLE_OBSOLETE_KEYIO is defined when (IMGUI_DISABLE_OBSOLETE_FUNCTIONS) is defined and this is used in standard cimgui generation and so should be used in compilation
> 
> https://github.com/cimgui/cimgui/blob/eb0649acf3a37d0d072d6b76fa51f9d851a04f33/backend_test/example_sdl_vulkan/CMakeLists.txt#L22

That seems to be what I was missing. Thanks!
