### ISSUE TITLE
glfw examples need STATIC compilation

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#270]
@ocornut

`Assertion failed: bd->PrevWndProc != nullptr, file C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\backends\imgui_impl_glfw.cpp, line 656`

is the assert resulting if glfw is linked not STATIC but SHARED

Any idea?

**Comment by ocornut** [comment]
No idea. It would mean the window has no installed WndProc which seems strange. I don't think it has anything to do with glfw linkage.

**Comment by sonoro1234** [comment]
But it does not happen when linkage is STATIC!!

**Comment by sonoro1234** [comment]
corrected: everything is linked dynamic or static.

It was failing when glfw was linked static but cimgui was linked dynamic.

**Comment by lj-cug** [comment]
Strange! Although I link cimgui and glfw3 both in static library, the same error happened! I use Fortran binding c code.

        subroutine ImGui_ImplGlfw_InitForOpenGL(window, install_callbacks)
            implicit none
            type(GLFWwindow), value, intent(in) :: window
            LOGICAL(c_bool), intent(in) :: install_callbacks   
            call c_ImGui_ImplGlfw_InitForOpenGL(window, install_callbacks)
        end subroutine ImGui_ImplGlfw_InitForOpenGL
Li

**Comment by sonoro1234** [comment]
What happens with dynamic?
