### ISSUE TITLE
Replace new with IM_NEW in cimgui_template.cpp

### ISSUE THREAD

**Issue by Coldzer0** [cimgui/cimgui#272]
I'm working on a FreePascal/Delphi binding for imgui using cimgui 

The FreePascal compiler has some problems with libc++ on Windows, so I wanted a cimgui static library that does not use libc++.

Which I already solved by using 
```
target_compile_options(cimgui PUBLIC -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics)
```
And changing `new` to `IM_NEW`.

https://github.com/cimgui/cimgui/blob/f6fb347cf11217d3ce59fd7956eb3aaf5724518d/generator/cimgui_template.cpp#L92

**Comment by sonoro1234** [comment]
Done!!
