### ISSUE TITLE
Adding comments in the generated C bindings

### ISSUE THREAD

**Issue by alexlnkp** [cimgui/cimgui#274]
As you may know, ImGui has a ton of comments in its header that help immensely when writing code. The comments tell you what field is for what, what function does what, sometimes even what are the parameters the function expects...
Knowing that, I'm puzzled because cimgui.h doesn't have any of the comments from the imgui.h file itself, practically forcing you to cross-reference the two all of the time, which isn't very convenient as it's much harder to pinpoint where a function is defined in imgui's sources while only knowing it's name.
I'm not sure about how the generator for c bindings work, unfortunately. However, if it's possible to include imgui.h's comments, that'd be wonderful! Another nice thing to have would be an original name of the imgui's function near a cimgui's function in the header, I.E. :
```c
// ImGui::NewFrame();
CIMGUI_API void igNewFrame(void);
```
That way, it's much easier for people to find the functions in cimgui if they've worked with imgui before.

**Comment by sonoro1234** [comment]
There is https://github.com/cimgui/cimgui/blob/35a4e8f8932c6395156ffacee288b9c30e50cb63/generator/generator.bat#L18

I prefer to text search NewFrame or whatever in imgui.h

**Comment by alexlnkp** [comment]
> There is
> 
> https://github.com/cimgui/cimgui/blob/35a4e8f8932c6395156ffacee288b9c30e50cb63/generator/generator.bat#L18
> 
> I prefer to text search NewFrame or whatever in imgui.h

Got it! Thanks for the help, I'm not very smart...
