### ISSUE TITLE
Using backends without CMake

### ISSUE THREAD

**Issue by brokenps2** [cimgui/cimgui#275]
I'm working on a project that does not use CMake, and its too late in development to change that. However, all the instructions for setting up the backends are specifically for projects using CMake. Is there any way I could set up a GLFW/OpenGL3 backed with a makefile?

**Comment by sonoro1234** [comment]
You could adapt [Makefile ](https://github.com/cimgui/cimgui/blob/docking_inter/Makefile) adding relevant backend files
