### ISSUE TITLE
generating latest docking creates invalid file

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimgui#277]
steps to reproduce:
- clone
- enter cimgui/imgui
- `git checkout docking; git pull`
- run generator
it will produce the following line in output cimgui.h
```h
typedef ImStb::STB_TexteditState ImStbTexteditState;
```
in `#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS` section Which is (imo) invalid for GCC

**Comment by sonoro1234** [comment]
I guess It is due to moving stb headers. I will have to investigate. 1.91.1dock is generating correctly

**Comment by sonoro1234** [comment]
Check again and report please

**Comment by gucio321** [comment]
works, thank you!

@sonoro1234 I have a question for you just by the way:
I created a few C wrappers of Dear ImGui plugins basing on this repo and [cimplot](https://github.com/cimgui/cimplot)
- https://github.com/gucio321/cimmarkdown
- https://github.com/gucio321/cimguizmo


the first one works +/- well, however I have some problems with the second:
generator crashes when I try to use it on header files with `#include <SomeC++Library>` (what makes sense as these libraries are not compilable with `gcc -E`) (I also tried to implement wraper for https://github.com/gucio321/cimgui-textedit but I experienced the same issue).

As a lua code author you are probably more suitable person to work with this code (my code experience is most likely printf-debugging, changing random things and seeing what happens :smile:) 
I can transfer my repos to this org btw so that other people who want to use them can easily find them.

**Comment by sonoro1234** [comment]
https://github.com/cimgui/cimguizmo

**Comment by gucio321** [comment]
oh I didn't see that, thank you!

**Comment by gucio321** [comment]
what about transferring cimmarkdown here?
and adding this https://github.com/BalazsJako/ImGuiColorTextEdit (we'd love to have it in cimgui-go ;-) )

**Comment by sonoro1234** [comment]
> oh I didn't see that, thank you!

There are even more repos in https://github.com/cimgui
They asume to be side by side with cimgui in order to use cpp2ffi.lua.
They are used in https://github.com/sonoro1234/LuaJIT-ImGui

> what about transferring cimmarkdown here?
> and adding this https://github.com/BalazsJako/ImGuiColorTextEdit (we'd love to have it in cimgui-go ;-) )

if they are succesful  in generation (perhaps taking cimguizmo as a model) it would be great

**Comment by gucio321** [comment]
> if they are succesful in generation (perhaps taking cimguizmo as a model) it would be great

meh, I can't transfer cimmarkdown as github asys I have no permission to do this. You might need just to fork that

**Comment by sonoro1234** [comment]
I should create it in cimgui organization so that you could fork and do pull requests.

**Comment by sonoro1234** [comment]
> and adding this https://github.com/BalazsJako/ImGuiColorTextEdit (we'd love to have it in cimgui-go ;-) )

ImGuiColorTextEdit has extensive use of std:string which is unportable to C without doing conversion from-to char*

**Comment by gucio321** [comment]
> > and adding this https://github.com/BalazsJako/ImGuiColorTextEdit (we'd love to have it in cimgui-go ;-) )
> 
> ImGuiColorTextEdit has extensive use of std:string which is unportable to C without doing conversion from-to char*

Is it possible to do this in C wrapper somehow?

**Comment by sonoro1234** [comment]
> Is it possible to do this in C wrapper somehow?

Could be but there is also std classes as map, pair, etc which seem more problematic.
As ImGuiColorTextEdit has not changed in several years perhaps a manual wrapping would be desirable.

**Comment by sonoro1234** [comment]
@gucio321 just added a manual C wrapping of ImGuiColorTextEdit in https://github.com/cimgui/cimCTE.
Just the minimum to run [cimCTEsample.lua](https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/examples/CTE_sample.lua) which is the Lua version of https://github.com/BalazsJako/ColorTextEditorDemo

**Comment by gucio321** [comment]
Wow, sounds awesome! Thank you, I'll check it out

**Comment by gucio321** [comment]
@sonoro1234 could you also add json files compatible with these from here?

**Comment by sonoro1234** [comment]
No, as it is manually generated

**Comment by gucio321** [comment]
I see. However I need it for compatibility with cimgui-go but I'll write it myself then.

**Comment by sonoro1234** [comment]
It is easy because it does not expose too much from `TextEditor.h`

**Comment by sonoro1234** [comment]
Issue solved
