### ISSUE TITLE
ImGUI Unity Web Assembly Question

### ISSUE THREAD

**Issue by gkaufman2026** [cimgui/cimgui#280]
I am trying to fix the Dear ImGui Unity repo to allow WebGL build, how can I do this?

I'm using this [repo](https://github.com/mattmanj17/dear-imgui-unity/tree/matthewd) based on a [Youtube video](https://www.youtube.com/watch?v=i9yjuJC11zU) I found. I'm generally just trying to find a way to integrate my project for WebGL for a school project. 

The library for WebGL is missing from the base repo. How can I build the library to work on Unity using the following link for integration? 

[IMGUI.net](https://github.com/mellinoe/ImGui.NET)

Any assistance is appreciated. Thank you.

**Comment by sonoro1234** [comment]
This seems an ImGuiNet question. Did you asked there? There are new ImGui.NET bindings in other places but I dont know if they are useful with Unity.

**Comment by sonoro1234** [comment]
Only related to cimgui is that for generate the wgpu backend you should add it in generator.bat.
Integration with imgui.net or unity is out of scope here.
