### ISSUE TITLE
Field accessors

### ISSUE THREAD

**Issue by mellinoe** [cimgui/cimgui#46]
How do other folks feel about exposing field accessors for structures in imgui? I've found that the most painful part of maintaining bindings is keeping structure definitions in sync. Having explicit accessor methods would help alleviate this, but it would be a very large addition. Perhaps it would only make sense to do this for a few common structures (IO, etc.).

Just to clarify, I'm referring to explicit get/set functions for fields. Something like this:

```C
CIMGUI_API igIO_GetDisplaySize(ImGuiIO* io)
{
    return io->DisplaySize;
}

CIMGUI_API igIO_SetDisplaySize(ImGuiIO* io, ImVec2 value)
{
    io->DisplaySize = value;
}
```

This would be resilient to changes in the format of the ImGuiIO structure.

How have other folks been handling this in their bindings?

**Comment by Extrawurst** [comment]
Good question, I dont know how other bindings handle that. But for me it feels like this would overblow the already huge API. How do others feel about that? I will leave it open for now to see more input on this topic

**Comment by Wizzard033** [comment]
This type of thing is auto-generated by a lot of binding tools, i.e. LuaJIT FFI.

**Comment by sonoro1234** [comment]
Dont overblow API please. Everything gets autogenerated from cimgui.h if ImGuiIO structure is updated in it and CIMGUI_DEFINE_ENUMS_AND_STRUCTS is defined.

**Comment by sonoro1234** [comment]
@mellinoe 
Now automatically in
https://github.com/sonoro1234/cimgui
