### ISSUE TITLE
New cimgui auto (1.62.0-beta) and imgui implementations

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#58]
Work on a cimgui automatic generation + imgui implementations can be found on
https://github.com/sonoro1234/cimgui

Example on using that for a LuaJIT binding is on
https://github.com/sonoro1234/LuaJIT-ImGui

I am most interested in getting feedback about overloaded function naming, constructors, building in other systems, etc ...

**Comment by Extrawurst** [comment]
Hi @sonoro1234 thanks for all the effort. Just tried your auto generated bindings! Amazing job!
Sorry for being so unresponsive. I am now wondering what to do with this repo here? What do you think about creating a github team/group and join efforts on this project, merging both of your repos to one reducing confusion on the end users side and retaining the gathered stars on this one here. also then we can have one c bindings link again on the official imgui readme.
Let me know what you think.

**Comment by sonoro1234** [comment]
```c
What do you think about creating a github team/group and join efforts on this project
```
It seems ok to me but I dont know how to do that (never done it before)

**Comment by Extrawurst** [comment]
No worries I will set that up today

**Comment by Extrawurst** [comment]
Created the cimgui org on GitHub and moved the project there and invited u

**Comment by sonoro1234** [comment]
PR #59 seems to solve, if it is ok confirm the merge

**Comment by Extrawurst** [comment]
thanks a lot! could we tag the right commits for the various imgui versions ?

**Comment by sonoro1234** [comment]
The tags are present in sonoro1234/cimgui/master.
I dont know how to set them in cimgui/cimgui

Readme.md should be changed a little to point to cimgui/cimgui (will make a PR)

**Comment by mellinoe** [comment]
Hey @sonoro1234 , super happy to see this got merged into master here. I noticed one little problem with a small number of generated functions. For example: [ColorConvertRGBToHSV](https://github.com/ocornut/imgui/blob/master/imgui.cpp#L1611) (and HSVToRGB). The `float&` parameters have simply turned into `float` parameters, which isn't correct. They should probably be converted into pointers. I don't think this affects very many functions, since references seem to be rare in the public API.

**Comment by sonoro1234** [comment]
@mellinoe see:
https://github.com/ocornut/imgui/issues/1879#issuecomment-406581391
Let me think what to do...

**Comment by sonoro1234** [comment]
@mellinoe 
As they are only two functions I setted them as manuals.
All functions implemented as manuals have now manual=true in the definitions.json

**Comment by Extrawurst** [comment]
> The tags are present in sonoro1234/cimgui/master.
> I dont know how to set them in cimgui/cimgui

we have to `git tag` the right commits (that got merged with the PR yesterday) accordingly here or we ditch the older ones and just set the current release tag (thats the minimum) here. after this we can finally close this ticket

**Comment by sonoro1234** [comment]
I cant set the tags with a PR
May be I have to push to cimgui/cimgui with includeTags?

**Comment by Extrawurst** [comment]
just like with any remote repo u can push the tags to cimgui/cimgui: 
`git push origin <tag u created locally>`

i made u a co-owner you can push directly to master aswell.

**Comment by sonoro1234** [comment]
Just done it.

It remains the issue that:

tags are misleading because people should use always the last generator version on whatever imgui version they desire just by updating imgui subproject

**Comment by Extrawurst** [comment]
Valid point. But we could create branches where we keep the generated cimgui-output for a specific (maybe the last 4) releases of imgui. we then could tag releases in there and for every new generator version we create a dot release like 1.60.x. that would be an extra effort and could not be easily automated. maybe we just do that for the latest releases and ditch the older ones prior to this. what do you think?

**Comment by sonoro1234** [comment]
Ok, lets do it for the next releases

**Comment by sonoro1234** [comment]
@mellinoe  see: https://github.com/ocornut/imgui/issues/2115

**Comment by sonoro1234** [comment]
@mellinoe ocornut already changed the definition
I have add some code to generator.lua to check this kind of issues.

I am closing this issue. Please open new ones for future communications ;-)
