### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ocornut** [cimgui/cimgui#65]
I think the instructions could be improved to be super explicit

- "clone" -> "show git cloning command-line" (include recursive remote)
- "make using..." -> "command-line for Windows, for Mac etc."
- explicit instructions to download and build luajit

Etc.
all those steps being super explicit would make a difference in adoption ihmo.

I am still trying to figure the steps for Windows and the generator is spitting out
```
HAVE_GCC        true
failure arg detection   BeginTabItem    nil     nil     (const char* label,bool* p_open,ImGuiTabItemFlags)      ImGuiTabItemFlags
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
../imgui/imgui.h:9:9: warning: #pragma once in main file
 #pragma once
         ^~~~
failure arg detection   return  nil     nil     (&x)    &x
reference to no const arg in    return  (&x)
failure arg detection   return  nil     nil     (&x)    &x
reference to no const arg in    return  (&x)
-----------------check arg detection---------------------------
bad argument name       nil     in      return  (x)
bad argument name       nil     in      return  (x)
-----------------end check arg detection-----------------------
luajit.exe: ./generator.lua:742: enum in struct
stack traceback:
        [C]: in function 'assert'
        ./generator.lua:742: in function 'gen_structs_and_enums_table'
        ./generator.lua:1234: in main chunk
        [C]: at 0x00d521f0
```

**Comment by sonoro1234** [comment]
I dont use command line git so I dont know what to say
The command for building is just: "make" (or "mingw32-make" in mingw)

**Comment by ocornut** [comment]
OK but if you want a software to be used by people it's good to make that effort of streamlining usage to the max, it's not really a hard task if you know what it needs.

Neither make, luajit or gcc comes with windows, so "make" doesn't work on many people PC. 
A simple two-step thing "how to get and install a version of make that works" would facilitate that.

(I'm myself going to try to add it in my frequent build script so I can catch some obvious errors easily.)

**Comment by sonoro1234** [comment]
But this is not for users!
Only programmers are going to use cimgui and they already have a building enviroment (which with the help of cmake can be almost anyone)

**Comment by sonoro1234** [comment]
which imgui version/branch gives the above generator output?

**Comment by ocornut** [comment]
This was `docking` yesterday. 
If I switch to master I get
```
HAVE_GCC        true
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
../imgui/imgui.h:9:9: warning: #pragma once in main file
 #pragma once
         ^~~~
failure arg detection   return  nil     nil     (&x)    &x
reference to no const arg in    return  (&x)
-----------------check arg detection---------------------------
bad argument name       nil     in      return  (x)
-----------------end check arg detection-----------------------
luajit.exe: ./generator.lua:742: enum in struct
stack traceback:
        [C]: in function 'assert'
        ./generator.lua:742: in function 'gen_structs_and_enums_table'
        ./generator.lua:1234: in main chunk
        [C]: at 0x010321f0

D:\T-Work\GitHub\cimgui\generator>copy .\generated\cimgui_auto.h ..\cimgui_auto.h
        1 file(s) copied.

D:\T-Work\GitHub\cimgui\generator>copy .\generated\cimgui_auto.cpp ..\cimgui_auto.cpp
        1 file(s) copied.
```

Using Mingw64 8.1 under Windows.

I also get a vastly different output for cimgui_auto.cpp (see diff attached, this is generated with unmodified cimgui repo), various missing stuff:
[regenerate_locally.zip](https://github.com/cimgui/cimgui/files/2449501/regenerate_locally.zip)

**Comment by sonoro1234** [comment]
I dont get that with 4.8.2 gcc but similar results with gcc 7.4.2
I will have to investigate
Thanks for reporting

**Comment by sonoro1234** [comment]
@ocornut  please check with last commit
issue should be solved, the only differences between different gcc should be slight variations in some numerical values

**Comment by ocornut** [comment]
Working better now!

```
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


HAVE_GCC        true
------------------generation without precompiler------------------------
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
------------------generation with precompiler------------------------
../imgui/imgui.h:9:9: warning: #pragma once in main file
 #pragma once
         ^~~~
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertRGBtoHSV    (float r,float g,float b,float& out_h,float& out_s,float& out_v)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
reference to no const arg in    ColorConvertHSVtoRGB    (float h,float s,float v,float& out_r,float& out_g,float& out_b)
-----------------check arg detection---------------------------
-----------------end check arg detection-----------------------
all done!!
```

The only two different files are definitions.json and definitions.lua, the .cpp files are identical.
In definitions.lua the FLT_MAX value are higher precision:

![image](https://user-images.githubusercontent.com/8225057/46531885-1c99d900-c89f-11e8-92c8-693b25900a53.png)

Maybe related to a LUA settings? Would be good to provide LUA-side settings/versions to ensure 100% consistent output.

Other things:
- I think the output filenames is wrong. The final output cimgui_auto.h/cpp should be `cimgui.h` `cimgui.cpp`, that's the one and only main file the end-user will need and care about. 
- The header for it should state that it is an auto-generated file, provide a link to the repo and show a version number.
- IMGUI_VERSION is not included in cimgui.h
- I'm not sure I understand why they are both "cimgui.cpp" and "cimgui_auto.cpp" in generator/ what is the difference/use?
- Since there is a single file, the instructions could also suggest that the user may drop that in along with e.g. the regular imgui.cpp file.
- What is `auto_funcs.cpp` included in `cimgui_template.cpp` ? The file doesn't exist.
- It would be good if every file has a small header including the filename and a description of what it is for.
- The `generator/generated` folder could be renamed to `generated/output`, also with added benefit that typing "gen" then TAB in a command-line will always lead you to the build script file.

**Comment by sonoro1234** [comment]
```
Maybe related to a LUA settings? Would be good to provide LUA-side settings/versions to ensure 100% consistent output.
```
Lua settings are the same, only preprocessor changes and FLT_MAX may have different definitions in each preprocessor.

```
- I think the output filenames is wrong. The final output cimgui_auto.h/cpp should be cimgui.h cimgui.cpp, that's the one and only main file the end-user will need and care about.
- I'm not sure I understand why they are both "cimgui.cpp" and "cimgui_auto.cpp" in generator/ what is the difference/use?
```
the first is without gcc preprocessing the second with gcc
the first is experimental and I will call it cimgui_nopreprocess, the second will be cimgui

```
- The header for it should state that it is an auto-generated file, provide a link to the repo and show a version number.
- IMGUI_VERSION is not included in cimgui.h
```
Yes
```
- It would be good if every file has a small header including the filename and a description of what it is for.
```
Do you mean every generated file?
```
- What is auto_funcs.cpp included in cimgui_template.cpp ? The file doesn't exist.
```
It is just a mark for generator.lua knowing where to insert function implementation.

```
- Since there is a single file, the instructions could also suggest that the user may drop that in along with e.g. the regular imgui.cpp file.
- The generator/generated folder could be renamed to generated/output, also with added benefit that typing "gen" then TAB in a command-line will always lead you to the build script file.
```
Sorry, I dont understand this to sentences

**Comment by ocornut** [comment]
I'm replacing the links on imgui's homepage/wiki now.

>> It would be good if every file has a small header
> Do you mean every generated file?

I mean every file, generated or not. Will help programmers digging into it. 

> Since there is a single file, the instructions could also suggest that the user may drop that in along with e.g. the regular imgui.cpp file.

The instruction says "make using makefile on linux/macOS/mingw (Or use CMake to generate project)" but users can just copy cimgui.cpp and cimgui.h and use as-is in their project without building a library?

> The generator/generated folder could be renamed to generated/output, also with added benefit that typing "gen" then TAB in a command-line will always lead you to the build script file.

I mean "generator/generated/" could be renamed to "generator/output/" which is easier to understand (and has the benefit that you can use auto-completion in this folder without "generated/" appearing before "generator.bat" when you press tab :)

Last thing, I think you could update the README to clearly explain the history of this "cimgui by Stephan Dilly turned into an auto-generated version by sonoro1234 etc." mainly so people understand WHY there is this new repository and understand the difference with Stephan Dilly's repository.

**Comment by ocornut** [comment]
Oh, I just realized that this repo was renamed from extrawurst/cimgui !
That's clarify things a bit :)

**Comment by mellinoe** [comment]
I'll just chime in my 2 cents, since I did manage to run the generator after some struggling.

* The gcc dependency is fairly painful / unnecessary. After 20 minutes of searching, I was unable to install gcc for Windows. Clang is significantly easier to install on Windows (not to mention I already had it). `clang -E` seems to be a drop-in replacement for `gcc -E`, because that was the only change I made and it worked.
* Regular lua.exe does not work, but I think some of the directions said that it should work. There were some extra utilities that luajit comes with that are needed. I can't recall what exactly they were. Long story short, you have to have luajit. If that's indeed the case, there should be a download link or something in the instructions. I used [this](https://luapower.com/) but I'm not sure if that was a good idea or not.
* There was some output in the console that I wasn't sure was bad or not. I believe it was related to `ColorConvertRGBtoHSV` as @ocornut posted above, although the exact message looked different from above (I think). It seems like it was some kind of error, as those functions are not properly handled as they contain references. Anyways, it would be good if the messages were more clear about whether they were describing errors, warnings, just informational, etc.
* 100% consistent output is really important, IMO. I'm guessing this might be related to compiler differences (?), so it may be tricky to sort out.

These are just small problems in the grand scheme of things. Overall this is going to be a fantastic tool.

**Comment by sonoro1234** [comment]
Thanks for reporting

>The gcc dependency is fairly painful / unnecessary. After 20 minutes of searching, I was unable to install gcc for Windows. Clang is significantly easier to install on Windows (not to mention I already had it). clang -E seems to be a drop-in replacement for gcc -E, because that was the only change I made and it worked.

see #67 
>Regular lua.exe does not work, but I think some of the directions said that it should work. There were some extra utilities that luajit comes with that are needed. I can't recall what exactly they were. Long story short, you have to have luajit. If that's indeed the case, there should be a download link or something in the instructions. I used this but I'm not sure if that was a good idea or not.

It is already on the README.md (not Lua5.1 and download links)

>There was some output in the console that I wasn't sure was bad or not. I believe it was related to ColorConvertRGBtoHSV as @ocornut posted above, although the exact message looked different from above (I think). It seems like it was some kind of error, as those functions are not properly handled as they contain references. Anyways, it would be good if the messages were more clear about whether they were describing errors, warnings, just informational, etc.

I will review that

>100% consistent output is really important, IMO. I'm guessing this might be related to compiler differences (?), so it may be tricky to sort out.

see #66

**Comment by ocornut** [comment]
I ought to clarify an idea - in my opinion the aim should be that _anyone_ can maintain their generated copy of cimgui based on any version of imgui. 

This is so users of cimgui can benefit from hot-fixes, can update mid-version which include support for changes which are breaking binary compatibility (changes of enum values, structure layout.), etc. If it's a pain to regenerate cimgui for the casual imgui user they are stuck with tagged releases and cimgui users are second class citizens. We ought to ideally remove that gap.

This is why it is important that the project runs everywhere and depend on as little amount of external tooling as possible. If you have a "no preprocessor" path I'd suggest to focus on that path and making it as good as the other paths so it becomes the unique path.

**Comment by sonoro1234** [comment]
Yes, it would be extremely desirable to have a well developed nopreprocessor path, that why I am still mantaining it. But unfortunately there are still small errors it it and I will always want to be able to compare them (having both) for some time.

**Comment by sonoro1234** [comment]
done

**Comment by sonoro1234** [comment]
also done nocompiler option

**Comment by sonoro1234** [comment]
readme updated with Information
