### ISSUE TITLE
Alternative preprocessors

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#67]
In order to have gcc alternatives for the preprocessing I would need the output of other preproccesors

As for the gcc alternatives it seems that cl /E (MSVC) does the same as gcc -E and also clang -E

Someone with this compilers would have to generate the output of

```
cl /E -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_API="" -DIMGUI_IMPL_API="" ../imgui/imgui.h
```
or any other compiler and attach it

**Comment by mellinoe** [comment]
When I was testing on Windows, `clang -E` worked as-is, without changing anything else in any of the scripts.

**Comment by ocornut** [comment]
I agree with Eric this should ideally stray away from relying on any preprocessor. It’s not very hard to rewrite a preprocessor especially since we have a known scope of what it has to handle.

**Comment by sonoro1234** [comment]
I dont undestand that mellinoe is saying to stay away from any preprocessor. Just that clang works also.
So I just did a commit to allow it.
(The way without compiler is in cimgui_NOpreprocessor)

**Comment by ocornut** [comment]
> "The gcc dependency is fairly painful / unnecessary. After 20 minutes of searching, I was unable to install gcc for Windows. Clang is significantly easier to install on Windows (not to mention I already had it). "

Well ideally being compiler depending would avoid install pain for windows users and help us guarantee consistent output regardless of the platform.

But if there is a choice to make between gcc and clang, totally go for clang :)

**Comment by sonoro1234** [comment]
clang is already allowed from the command line
https://github.com/cimgui/cimgui/blob/master/generator/generator.bat#L17

cl (msvc) would be good to have
but I am still needing the output of
```
cl /E -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_API="" -DIMGUI_IMPL_API="" ../imgui/imgui.h
```
to investigate
and also the equivalent of gcc/clang -dM option for only getting defines

**Comment by sonoro1234** [comment]
@mellinoe @ocornut 
The commit for allowing cl as preproccesor is done.
The only that does not work is getting FLT_MAX value because there is not -dM option
(Installing took much more than 20 minutes)

**Comment by sonoro1234** [comment]
Also implemented nocompiler option
