### ISSUE TITLE
ImDrawIdx declaration

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#77]
@ocornut

ideally

>#ifndef ImDrawIdx
typedef unsigned short ImDrawIdx;
#endif

should be moved before `ImVector` declaration in imgui.h so that when I declare
`ImVector_ImDrawIdx` for `ImVector<ImDrawIdx>`
`ImDrawIdx` is already declared

Now I can make it work with the trick of programatically moving this declarations but I think that the other way would be cleaner
Dont you?

**Comment by ocornut** [comment]
Can't you just forward declare it?

**Comment by ocornut** [comment]
I'm not sure I understand how it'll work since you don't have the `#ifndef ImDrawIdx` block in cimgui.h. That block is missing. If you are going to add this, just add it before the ImVector_ImDrawIdx declaration?

**Comment by ocornut** [comment]
I don't understand what you mean by "move" since the ifdef _hasn't been added_ to cimgui,h.

It is at the right place from the point of view of imgui.h, we can't be altering imgui.h readability sorry.
