### ISSUE TITLE
"Invalid DisplaySize value" assertion failed via glew and gl3w

### ISSUE THREAD

**Issue by haxpor** [cimgui/cimgui#79]
I tested with SDL2 (2.0.9 9bb50edccc46) on macOS 10.14 (18A391) and ported [imgui_impl_opengl3.h](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl3.h), [imgui_impl_opengl3.cpp](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl3.cpp), and [main.cpp](https://github.com/ocornut/imgui/blob/master/examples/example_sdl_opengl3/main.cpp) to C (checked calling to cimgui properly).

I faced with the problem of 

```
Assertion failed: (g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value"), function NewFrame, file imgui/imgui.cpp, line 3090.
Abort trap: 6
```

Download the project: [cimgui-sdl2.tar.gz](https://github.com/cimgui/cimgui/files/2527046/cimgui-sdl2.tar.gz).

To build, simply ...

* `make` to build against `gl3w`
* `make glew` to build against `glew`

ps. 
- notice that I have to do relative-path symlink `cimgui.dylib` as `libcimgui.dylib`, related to #78 .
- X11 is installed at `/opt/X11` and its `include` directory is added in Makefile as well.

**Comment by sonoro1234** [comment]
I cant compile as I am on windows
It is a imgui issue (not cimgui)
I searched in imgui and got only this https://github.com/ocornut/imgui/issues/1562
something must be wrong in your edited files?

**Comment by sonoro1234** [comment]
```
ImVec2 vec;
    vec.x = (float)w;
    vec.y = (float)h;
    io.DisplaySize = vec;

    vec.x = w > 0 ? ((float)display_w / w) : 0;
    vec.y = h > 0 ? ((float)display_h / h) : 0;
    io.DisplayFramebufferScale = vec;
```
This could be wrong
In C `io.DisplaySize = vec;` is not a copy constructor so I think you get the same on both DisplaySize and DisplayFramebufferScale

Try to only rewrite main.c

**Comment by sonoro1234** [comment]
Also in
```
ImGuiIO io = *igGetIO();
io.DisplaySize = vec;
```
you are not modifying original ImGuiIO
perhaps
```
ImGuiIO *io = igGetIO();
io->DisplaySize = vec;
or
io->DisplaySize.x = (float)w;
```
Main recomendation: Try to only rewrite main.c

**Comment by haxpor** [comment]
Thank you so much for your time checking this out!
You shed the light for me as I overlook that in fact I can keep SDL's implementation for imgui code intact, and compile then into object files or library then link it to our main C source.

I made it work regarding to your suggestion to not modify anything.
To keep this as a record, there are 2 things I need to do to make it works

1. I have to slightly modify `imgui_impl_sdl.h` and `imgui_impl_sdl.cpp` to put `struct` in front of `SDL_Wnidow` in function declaration.
2. Add `-DIMGUI_IMPL_API="extern \"C\""` for compile flags when compile both of `imgui_impl_sdl` and `imgui_impl_opengl3`. To make it provide C interface to work with C source code.
3. In linking to our main source code, I need to also add `-lc++` so it won't shout out undefined symbols.

I attached working test project: [cimgui-sdl2.tar.gz](https://github.com/cimgui/cimgui/files/2530317/cimgui-sdl2.tar.gz)
(same make command for either gl3w or glew).

Thanks for the help and cimgui. It all works fine now.

**Comment by sonoro1234** [comment]
I am C++ compiling this in
https://github.com/sonoro1234/LuaJIT-ImGui/blob/master_auto_implementations/CMakeLists.txt
without any file modification, only IMGUI_IMPL_API definition

Then to use it from C the header should be https://github.com/cimgui/cimgui/blob/master/generator/output/cimgui_impl.h

**Comment by haxpor** [comment]
Thanks! Looking at them, it's clear to me now.
