### ISSUE TITLE
MSVC: ImNewDummy requires at least one member

### ISSUE THREAD

**Issue by Helco** [cimgui/cimgui#80]
On master (4397288) trying to include cimgui.h from a C source file with MSVC and `CIMGUI_DEFINE_ENUMS_AND_STRUCTS` defined fails with the following error:

```
c:\[...]\cimgui\cimgui.h(591): error C2016: C requires that a struct or union has at least one member
```

In this header file `ImNewDummy` does not seem to be used anywhere?
My current hacky workaround is to define this line before include `cimgui.h`

```
#define ImNewDummy __ImNewDummyHack { int dummy; }; static void __ImNewDummyHack__##__FILE__ ()
```

**Comment by sonoro1234** [comment]
Thank for reporting
Jus commited
