### ISSUE TITLE
Compiling with GLEW support

### ISSUE THREAD

**Issue by vadtec** [cimgui/cimgui#89]
After much frustration and research, I've gotten the code to compile into a DLL/.so, which also includes compiling in the OpenGL/GLFW implementation code in the examples/ directory.

I'm not sure if the issue I'm having will be something that can be addressed here, or if it's left up to the coder.

I digress.

When I build the DLL, I'm linking in my compiled glew.o so that the DLL knows about the GLEW symbols. However, when I try to use the DLL, the glewInit() function is never called from within the DLL, so it never initializes the OpenGL/GLEW stuff, and things like glCreateShader() are ultimately NULL, which causes epic segfaults.

I looked around for a function that could be called to initialize GLEW from within the DLL, but did not find one. Rather than writing a function in CIMGUI to do this (since 1) I really don't think this is in the realm of the CIMGUI lib's intended scope, and 2) I don't want to have to do it every time I ugprade CIMGUI), I instead decided to compile the CIMGUI code directly into my binary.

For one, I really don't want the bloat of CIMGUI directly in my binary. Since CIMGUI makes calls that inlcude imgui_demo.cpp, there is a large amount of bloat. Again, I don't want to have to modify the CIMGUI code every time it's upgraded to remove the calls to the demo code to shrink the code base.

For two, if GLEW is going to be supported it should have some mechanism to initalize it from within a DLL/.so.

I have not used, nor do I intend to, GL3W or GLAD. To that end, I do not know if this is an issue that is specific to GLEW that I will simply have to work around. Any help with this would be greatly appreciated.

My main issue with CIMGUI at this point is this: it's use cases are extremely dependent upon your coding style. I've looked at your LuaJIT-cimgui to figure out how to build the DLL/.so that includes the implementations, and it seems highly specific to a single use case. I realize that you primarily use CIMGUI for your own uses, but when you say "look at X project for examples", said projects don't lend themselves to being very informative either.

In saying that, if I can find the time, I will try to improve the docs to provide some examples of general use cases. And, if I can come up with an acceptable method of building a DLL/.so that can initialize GLEW without requiring mods to CIMGUI itself, I will provide it as well. Same goes for stripping out the code from imgui_demo.cpp (for when you don't need it in production).

Now that I've spent some time figuring out how to use CIMGUI I do enjoy using it. I just think the docs need some polishing and the focus of the project needs to be expanded slightly to be more "general use" in nature.

**Comment by vadtec** [comment]
Regarding the compilation of imgui_demo.cpp being required as part of CIMGUI.

A simple flag to exclude it from being included in the generated output would be most efficient.

**Comment by sonoro1234** [comment]
> the glewInit() function is never called from within the DLL,

cimgui only cares about functions in imgui.h. You should do that yourself from your main function.

> I don't want to have to modify the CIMGUI code every time it's upgraded to remove the calls to the demo code to shrink the code base.

A build time flag could be created to disallow imgui_demo inclusion

**Comment by vadtec** [comment]
> 
> A build time flag could be created to disallow imgui_demo inclusion.
> But according to https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L11
> the first try should be to use the IMGUI_DISABLE_DEMO_WINDOWS flag at compile time

Hrm. Apologies. I remember reading this, but then have apparently forgotten about it.

Personally, I still think an option to exclude it entirely would be beneficial, but my project goals are to achieve maximum optimization across all metrics.

**Comment by vadtec** [comment]
> 
> cimgui only cares about functions in imgui.h. You should do that yourself from your main function.
> 

I should have mentioned that I'm not building a DLL version of GLEW. I simply compile it to object code and include it where it's needed. So, the DLL has it's own copy of GLEW that must be initialized. I created a function in my own code that gets shoved into the DLL that does the glewInit() inside the DLL and everything is working like a charm. Not exactly the most optimum solution, but it's what I'm working with for now. I'll build a DLL version of GLEW later and fix this issue completely.
