### ISSUE TITLE
ImVector question (new ImVector Branch)

### ISSUE THREAD

**Issue by vadtec** [cimgui/cimgui#90]
I'm following the demos from imgui_demo.cpp, and the log window is giving me some fits.
I've figured out how to handle ImGuiTextBuffer and ImGuiTextFilter in C code. But ImVector<int> is giving me all kinds of hell.
Am I missing some functionality, or am I assuming correctly that the note about ImVector from the readme should tell me that handling of ImVector is incomplete?
Specifically, I am looking at [this line](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L3413) of code.
If ImVector isn't suitable for use without doing something similar to ImVector_ImWchar I can work around it. I just want to be sure I'm not missing some functionality somewhere in the code. (Though I'm 99% certain it's not there.)

**Comment by sonoro1234** [comment]
> or am I assuming correctly that the note about ImVector from the readme should tell me that handling of ImVector is incomplete?

Yes, you are reading correctly from readme.md
```
All functions are programmatically wrapped except ImVector constructors and destructors. (Unless someone find a use case for them)(Now they exist for ImVector_ImWchar) 
```
I asked about ImVector use cases in previous issues but nobody had asked for this functionallity before.
They can be manually copied from ImVector_ImWchar or they could also be automatically generated if you found a use case for it.

**Comment by vadtec** [comment]
That would be great.
In the interest of completeness, would adding the same for all of the ImVector* be possible?

**Comment by sonoro1234** [comment]
That´s my intention. It will perhaps take some days.

**Comment by vadtec** [comment]
I appreciate it.

**Comment by sonoro1234** [comment]
@ocornut I am most confused by
https://github.com/ocornut/imgui/blob/7a5058e3bfea4149acef2ad98d8fdd62605a0f4c/imgui.h#L1192
in which two functions only differ by return type which I though was illegal overloading (And it is obviously not as ImGui is using it)
Could you share any link that gives me light.

**Comment by ocornut** [comment]
One is marked const not the other.

**Comment by sonoro1234** [comment]
Here
https://www.geeksforgeeks.org/function-overloading-and-const-functions/
is an explanation, so that the const function will be called when it is used on a const ImVector?

**Comment by ocornut** [comment]
Yes or when called thru a const pointer.

**Comment by sonoro1234** [comment]
How should be this wrapping
```cpp
CIMGUI_API const ImFont** ImVector_ImFontPtr_begin_const(const ImVector_ImFontPtr* self)
{
    return self->begin();
}
```
to avoid:
```
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp: In function 'const ImFont** ImVector_ImFontPtr_begin_const(const ImVector_ImFontPtr*)':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:3096:24: error: invalid conversion from 'ImFont* cons
t*' to 'const ImFont**' [-fpermissive]
     return self->begin();
```

**Comment by sonoro1234** [comment]
@vadtec 

Commenting out ImVector:contains() wrappings, branch ImVector compiles althought it is not tested for runtime errors. Perhaps you could test it.

**Comment by vadtec** [comment]
@sonoro1234 

I will test it either tonight or this weekend. Depends on work schedule.

**Comment by ocornut** [comment]
> Does it means that `const T*` when T is ImFont* means `ImFont* const *`?

`begin()` should return a pointer to the first element of the vector (essentially it returns ->Data). So when T is `ImFont*` const ImVector<>::begin() will return a `const ImFont**`. 
I don't know what is the `self->begin()` you are calling in your code. You can just return self->Data.

**Comment by sonoro1234** [comment]
@ocornut Did you see?

ImVector:contains() is not used in the whole imgui codebase. Could it be an imgui error?

**Comment by ocornut** [comment]
I'm using it in different branches. And being a common public utility, I cannot remove it from the API even if I wanted to.

**Comment by ocornut** [comment]
Normally the function should only be instanced when used for a certain type.
It's certainly not used with ImFontConfig.
AFAIK this is correct C++ behavior? You can remove this functions from the cimgui version?

**Comment by sonoro1234** [comment]
Yes, I will do that.

**Comment by sonoro1234** [comment]
> const ImVector<>::begin() will return a `const ImFont**`.

Thats what I thougth but it is not:
`const ImFont**` is a pointer to a pointer of a const ImFont and is equivalent to `ImFont const **`
what is returned is
`ImFont* const *` a pointer to a constant pointer of an ImFont (corresponding to `const T*` being T an ImFont*)

more on this in
https://stackoverflow.com/questions/1143262/what-is-the-difference-between-const-int-const-int-const-and-int-const
So I had to move const keyword because just plain text substitution dont works in this case.

**Comment by vadtec** [comment]
The first issue I ran into is this:
`
/the/path/source/cimgui/cimgui.h:848:55: error: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
         union { int val_i; float val_f; void* val_p; };
`

[this line](https://github.com/cimgui/cimgui/blob/186ebd8f06cd45f5eb927753696f30a89b449a91/generator/output/cimgui.h#L848) in cimgui.h

I run with -std=c99, -Wall, all the extra warnings, and -Wpedantic. I fix this particular issue by adding _pair just before the ;. I haven't used Pair yet, but I'm fairly certain this is going to cause issues.

I am still testing the rest of the code to see if ImVector is working under run conditions.

**Comment by sonoro1234** [comment]
@ocornut 
Above comment is related to issue #88
With -std=c99 -Wall -Wpedantic I am not getting error but a warning with mingw-w64
```
In file included from cimguitest.c:1:0:
../cimgui.h:848:55: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
         union { int val_i; float val_f; void* val_p; };
```

**Comment by vadtec** [comment]
Quick side note: I generated an implementation using luajit ./generator2.lua nocompiler glfw opengl3. I had to do this because I ran into typedef issues (see below) related to GLFW, which then caused SDL to give me issues. (BTW: generator2.lua worked many times better than the first time I tried to use it. Not sure if anything changed, but I didn't have a single issue with it this go round.)

I've run into another set of issues.

1) cimgui.h use to include cimgui_impl.h at the end of the file. It no longer does, at least in commit 186ebd8f06cd45f5eb927753696f30a89b449a91. Easy enough fix, just include it myself.

2) When doing that, I get the following:

```
/the/path/source/cimgui/cimgui_impl.h:2:27: error: redefinition of typedef 'GLFWwindow' [-Wpedantic]
 typedef struct GLFWwindow GLFWwindow;

/the/path/build/windows/x86_64/client/debug/include/GLFW/glfw3.h:789:27: note: previous declaration of 'GLFWwindow' was here
 typedef struct GLFWwindow GLFWwindow;
```

Redefining typedefs, even if they are exactly the same, is illegal in C.

Couple of suggestions. Frist, cimgui_impl.h needs some #ifndef/#define/#endif protection. Second, the two typedefs for SDL_Window and GLFWwindow (depending on your implementation needs) need to have some protection. I added this by doing the following:

```
#ifdef __cplusplus
typedef struct GLFWwindow GLFWwindow;
#endif
```

Once I resolved those few minor issues and figured out which set of functions to call, everything compiled just fine. I'm currently refactoring the code I was using to use the new ImVector* code. Give me just a bit and I'll let you know.

**Comment by vadtec** [comment]
> With -std=c99 -Wall -Wpedantic I am not getting error but a warning with mingw-w64
> @vadtec what is your compiler?

@sonoro1234 On Windows it is MinGW-64 (via MSYS2). Otherwise on my Ubuntu laptop it is simple gcc. I haven't compiled this code on Ubuntu in a while, so I don't know if it gives off the same error. (I assume it would since it's a C issue more so than a compiler issue.)

**Comment by vadtec** [comment]
@sonoro1234 So far, what I have tested using ImVector_int to implement the vector as in imgui_demo.cpp for the "app log" is working great.

Is there any way to group all the various ImVector_* types into the same location in the header file? Currently, the related functions (ImVector_int_push_back and such) are spread out over many lines, and finding all of them is somewhat cumbersome.

I will leave this issue open for a few days while I work with the code some more and do my best to test more of it.

Thanks for the help, I do appreciate it.

(Just as an FYI: I was using [this C style vector implementation](https://github.com/rxi/vec) to work around not having direct access to vectors via cimgui. Slightly cumbersome, but it works like a champ.)

**Comment by sonoro1234** [comment]
> 1. cimgui.h use to include cimgui_impl.h at the end of the file. It no longer does

It never has done as you can check in master branch. `typedef struct GLFWwindow GLFWwindow;` could just be dropped as glfw3.h already does this typedef.

> Is there any way to group all the various ImVector_* types into the same location in the header file? Currently, the related functions (ImVector_int_push_back and such) are spread out over many lines, and finding all of them is somewhat cumbersome.

All the different implementations of a function are grouped.

**Comment by vadtec** [comment]
> It never has done as you can check in master branch. `typedef struct GLFWwindow GLFWwindow;` could just be dropped as glfw3.h already does this typedef.

Hmm. In my previous copy of cimgui.h it had #include "cimgui_impl.h" at the bottom. I'll admit, I may have added that myself and just not remember.

> 
> All the different implementations of a ImVector function are grouped, instead of groupping by template type.

Regarding what I meant by grouping....I realize that all the functions are in the same location within the file, generally speaking. But for example, the difference in location between ImVectory_float_destroy() and ImVector_float_ImVector_floatVector() is 33 lines. The difference between ImVector_float_ImVector_floatVector() and ImVector_float_empty() is 17 lines. This doesn't lend it self to finding all the relevant functions for the same vector types easily. What I'm suggesting is the following.

Rather than having this (subset of all functions selected):

```
CIMGUI_API ImVector_float* ImVector_float_ImVector_float(void);
CIMGUI_API void ImVector_float_destroy(ImVector_float* self);
CIMGUI_API ImVector_ImWchar* ImVector_ImWchar_ImVector_ImWchar(void);
CIMGUI_API void ImVector_ImWchar_destroy(ImVector_ImWchar* self);
CIMGUI_API ImVector_ImFontConfig* ImVector_ImFontConfig_ImVector_ImFontConfig(void);
CIMGUI_API void ImVector_ImFontConfig_destroy(ImVector_ImFontConfig* self);
CIMGUI_API ImVector_ImFontGlyph* ImVector_ImFontGlyph_ImVector_ImFontGlyph(void);
CIMGUI_API void ImVector_ImFontGlyph_destroy(ImVector_ImFontGlyph* self);
CIMGUI_API ImVector_TextRange* ImVector_TextRange_ImVector_TextRange(void);
CIMGUI_API void ImVector_TextRange_destroy(ImVector_TextRange* self);
CIMGUI_API ImVector_CustomRect* ImVector_CustomRect_ImVector_CustomRect(void);
CIMGUI_API void ImVector_CustomRect_destroy(ImVector_CustomRect* self);
CIMGUI_API ImVector_ImDrawChannel* ImVector_ImDrawChannel_ImVector_ImDrawChannel(void);
CIMGUI_API void ImVector_ImDrawChannel_destroy(ImVector_ImDrawChannel* self);
CIMGUI_API ImVector_char* ImVector_char_ImVector_char(void);
CIMGUI_API void ImVector_char_destroy(ImVector_char* self);
CIMGUI_API ImVector_ImTextureID* ImVector_ImTextureID_ImVector_ImTextureID(void);
CIMGUI_API void ImVector_ImTextureID_destroy(ImVector_ImTextureID* self);
CIMGUI_API ImVector_ImDrawVert* ImVector_ImDrawVert_ImVector_ImDrawVert(void);
CIMGUI_API void ImVector_ImDrawVert_destroy(ImVector_ImDrawVert* self);
CIMGUI_API ImVector_int* ImVector_int_ImVector_int(void);
CIMGUI_API void ImVector_int_destroy(ImVector_int* self);
CIMGUI_API ImVector_Pair* ImVector_Pair_ImVector_Pair(void);
CIMGUI_API void ImVector_Pair_destroy(ImVector_Pair* self);
CIMGUI_API ImVector_ImFontPtr* ImVector_ImFontPtr_ImVector_ImFontPtr(void);
CIMGUI_API void ImVector_ImFontPtr_destroy(ImVector_ImFontPtr* self);
CIMGUI_API ImVector_ImVec4* ImVector_ImVec4_ImVector_ImVec4(void);
CIMGUI_API void ImVector_ImVec4_destroy(ImVector_ImVec4* self);
CIMGUI_API ImVector_ImDrawCmd* ImVector_ImDrawCmd_ImVector_ImDrawCmd(void);
CIMGUI_API void ImVector_ImDrawCmd_destroy(ImVector_ImDrawCmd* self);
CIMGUI_API ImVector_ImDrawIdx* ImVector_ImDrawIdx_ImVector_ImDrawIdx(void);
CIMGUI_API void ImVector_ImDrawIdx_destroy(ImVector_ImDrawIdx* self);
CIMGUI_API ImVector_ImVec2* ImVector_ImVec2_ImVector_ImVec2(void);
CIMGUI_API void ImVector_ImVec2_destroy(ImVector_ImVec2* self);
CIMGUI_API ImVector_float* ImVector_float_ImVector_floatVector(const ImVector_float src);
CIMGUI_API ImVector_ImWchar* ImVector_ImWchar_ImVector_ImWcharVector(const ImVector_ImWchar src);
CIMGUI_API ImVector_ImFontConfig* ImVector_ImFontConfig_ImVector_ImFontConfigVector(const ImVector_ImFontConfig src);
CIMGUI_API ImVector_ImFontGlyph* ImVector_ImFontGlyph_ImVector_ImFontGlyphVector(const ImVector_ImFontGlyph src);
CIMGUI_API ImVector_TextRange* ImVector_TextRange_ImVector_TextRangeVector(const ImVector_TextRange src);
CIMGUI_API ImVector_CustomRect* ImVector_CustomRect_ImVector_CustomRectVector(const ImVector_CustomRect src);
CIMGUI_API ImVector_ImDrawChannel* ImVector_ImDrawChannel_ImVector_ImDrawChannelVector(const ImVector_ImDrawChannel src);
CIMGUI_API ImVector_char* ImVector_char_ImVector_charVector(const ImVector_char src);
CIMGUI_API ImVector_ImTextureID* ImVector_ImTextureID_ImVector_ImTextureIDVector(const ImVector_ImTextureID src);
CIMGUI_API ImVector_ImDrawVert* ImVector_ImDrawVert_ImVector_ImDrawVertVector(const ImVector_ImDrawVert src);
CIMGUI_API ImVector_int* ImVector_int_ImVector_intVector(const ImVector_int src);
CIMGUI_API ImVector_Pair* ImVector_Pair_ImVector_PairVector(const ImVector_Pair src);
CIMGUI_API ImVector_ImFontPtr* ImVector_ImFontPtr_ImVector_ImFontPtrVector(const ImVector_ImFontPtr src);
CIMGUI_API ImVector_ImVec4* ImVector_ImVec4_ImVector_ImVec4Vector(const ImVector_ImVec4 src);
CIMGUI_API ImVector_ImDrawCmd* ImVector_ImDrawCmd_ImVector_ImDrawCmdVector(const ImVector_ImDrawCmd src);
CIMGUI_API ImVector_ImDrawIdx* ImVector_ImDrawIdx_ImVector_ImDrawIdxVector(const ImVector_ImDrawIdx src);
CIMGUI_API ImVector_ImVec2* ImVector_ImVec2_ImVector_ImVec2Vector(const ImVector_ImVec2 src);
CIMGUI_API bool ImVector_float_empty(const ImVector_float* self);
CIMGUI_API bool ImVector_ImWchar_empty(const ImVector_ImWchar* self);
CIMGUI_API bool ImVector_ImFontConfig_empty(const ImVector_ImFontConfig* self);
CIMGUI_API bool ImVector_ImFontGlyph_empty(const ImVector_ImFontGlyph* self);
CIMGUI_API bool ImVector_TextRange_empty(const ImVector_TextRange* self);
CIMGUI_API bool ImVector_CustomRect_empty(const ImVector_CustomRect* self);
CIMGUI_API bool ImVector_ImDrawChannel_empty(const ImVector_ImDrawChannel* self);
CIMGUI_API bool ImVector_char_empty(const ImVector_char* self);
CIMGUI_API bool ImVector_ImTextureID_empty(const ImVector_ImTextureID* self);
CIMGUI_API bool ImVector_ImDrawVert_empty(const ImVector_ImDrawVert* self);
CIMGUI_API bool ImVector_int_empty(const ImVector_int* self);
CIMGUI_API bool ImVector_Pair_empty(const ImVector_Pair* self);
CIMGUI_API bool ImVector_ImFontPtr_empty(const ImVector_ImFontPtr* self);
CIMGUI_API bool ImVector_ImVec4_empty(const ImVector_ImVec4* self);
CIMGUI_API bool ImVector_ImDrawCmd_empty(const ImVector_ImDrawCmd* self);
CIMGUI_API bool ImVector_ImDrawIdx_empty(const ImVector_ImDrawIdx* self);
CIMGUI_API bool ImVector_ImVec2_empty(const ImVector_ImVec2* self);
```

It would be much more readable to have this:

```
CIMGUI_API ImVector_float* ImVector_float_ImVector_float(void);
CIMGUI_API void ImVector_float_destroy(ImVector_float* self);
CIMGUI_API ImVector_float* ImVector_float_ImVector_floatVector(const ImVector_float src);
CIMGUI_API bool ImVector_float_empty(const ImVector_float* self);

CIMGUI_API ImVector_ImWchar* ImVector_ImWchar_ImVector_ImWchar(void);
CIMGUI_API ImVector_ImWchar* ImVector_ImWchar_ImVector_ImWcharVector(const ImVector_ImWchar src);
CIMGUI_API void ImVector_ImWchar_destroy(ImVector_ImWchar* self);
CIMGUI_API bool ImVector_ImWchar_empty(const ImVector_ImWchar* self);

CIMGUI_API ImVector_ImFontConfig* ImVector_ImFontConfig_ImVector_ImFontConfig(void);
CIMGUI_API void ImVector_ImFontConfig_destroy(ImVector_ImFontConfig* self);
CIMGUI_API ImVector_ImFontConfig* ImVector_ImFontConfig_ImVector_ImFontConfigVector(const ImVector_ImFontConfig src);
CIMGUI_API bool ImVector_ImFontConfig_empty(const ImVector_ImFontConfig* self);

CIMGUI_API ImVector_ImFontGlyph* ImVector_ImFontGlyph_ImVector_ImFontGlyph(void);
CIMGUI_API void ImVector_ImFontGlyph_destroy(ImVector_ImFontGlyph* self);
CIMGUI_API ImVector_ImFontGlyph* ImVector_ImFontGlyph_ImVector_ImFontGlyphVector(const ImVector_ImFontGlyph src);
CIMGUI_API bool ImVector_ImFontGlyph_empty(const ImVector_ImFontGlyph* self);

CIMGUI_API ImVector_TextRange* ImVector_TextRange_ImVector_TextRange(void);
CIMGUI_API void ImVector_TextRange_destroy(ImVector_TextRange* self);
CIMGUI_API ImVector_TextRange* ImVector_TextRange_ImVector_TextRangeVector(const ImVector_TextRange src);
CIMGUI_API bool ImVector_TextRange_empty(const ImVector_TextRange* self);

CIMGUI_API ImVector_CustomRect* ImVector_CustomRect_ImVector_CustomRect(void);
CIMGUI_API void ImVector_CustomRect_destroy(ImVector_CustomRect* self);
CIMGUI_API ImVector_CustomRect* ImVector_CustomRect_ImVector_CustomRectVector(const ImVector_CustomRect src);
CIMGUI_API bool ImVector_CustomRect_empty(const ImVector_CustomRect* self);

CIMGUI_API ImVector_ImDrawChannel* ImVector_ImDrawChannel_ImVector_ImDrawChannel(void);
CIMGUI_API void ImVector_ImDrawChannel_destroy(ImVector_ImDrawChannel* self);
CIMGUI_API ImVector_ImDrawChannel* ImVector_ImDrawChannel_ImVector_ImDrawChannelVector(const ImVector_ImDrawChannel src);
CIMGUI_API bool ImVector_ImDrawChannel_empty(const ImVector_ImDrawChannel* self);

CIMGUI_API ImVector_char* ImVector_char_ImVector_char(void);
CIMGUI_API void ImVector_char_destroy(ImVector_char* self);
CIMGUI_API ImVector_char* ImVector_char_ImVector_charVector(const ImVector_char src);
CIMGUI_API bool ImVector_char_empty(const ImVector_char* self);

CIMGUI_API ImVector_ImTextureID* ImVector_ImTextureID_ImVector_ImTextureID(void);
CIMGUI_API void ImVector_ImTextureID_destroy(ImVector_ImTextureID* self);
CIMGUI_API ImVector_ImTextureID* ImVector_ImTextureID_ImVector_ImTextureIDVector(const ImVector_ImTextureID src);
CIMGUI_API bool ImVector_ImTextureID_empty(const ImVector_ImTextureID* self);

CIMGUI_API ImVector_ImDrawVert* ImVector_ImDrawVert_ImVector_ImDrawVert(void);
CIMGUI_API void ImVector_ImDrawVert_destroy(ImVector_ImDrawVert* self);
CIMGUI_API ImVector_ImDrawVert* ImVector_ImDrawVert_ImVector_ImDrawVertVector(const ImVector_ImDrawVert src);
CIMGUI_API bool ImVector_ImDrawVert_empty(const ImVector_ImDrawVert* self);

CIMGUI_API ImVector_int* ImVector_int_ImVector_int(void);
CIMGUI_API void ImVector_int_destroy(ImVector_int* self);
CIMGUI_API ImVector_int* ImVector_int_ImVector_intVector(const ImVector_int src);
CIMGUI_API bool ImVector_int_empty(const ImVector_int* self);

CIMGUI_API ImVector_Pair* ImVector_Pair_ImVector_Pair(void);
CIMGUI_API void ImVector_Pair_destroy(ImVector_Pair* self);
CIMGUI_API ImVector_Pair* ImVector_Pair_ImVector_PairVector(const ImVector_Pair src);
CIMGUI_API bool ImVector_Pair_empty(const ImVector_Pair* self);

CIMGUI_API ImVector_ImFontPtr* ImVector_ImFontPtr_ImVector_ImFontPtr(void);
CIMGUI_API void ImVector_ImFontPtr_destroy(ImVector_ImFontPtr* self);
CIMGUI_API ImVector_ImFontPtr* ImVector_ImFontPtr_ImVector_ImFontPtrVector(const ImVector_ImFontPtr src);
CIMGUI_API bool ImVector_ImFontPtr_empty(const ImVector_ImFontPtr* self);

CIMGUI_API ImVector_ImVec4* ImVector_ImVec4_ImVector_ImVec4(void);
CIMGUI_API void ImVector_ImVec4_destroy(ImVector_ImVec4* self);
CIMGUI_API ImVector_ImVec4* ImVector_ImVec4_ImVector_ImVec4Vector(const ImVector_ImVec4 src);
CIMGUI_API bool ImVector_ImVec4_empty(const ImVector_ImVec4* self);

CIMGUI_API ImVector_ImDrawCmd* ImVector_ImDrawCmd_ImVector_ImDrawCmd(void);
CIMGUI_API void ImVector_ImDrawCmd_destroy(ImVector_ImDrawCmd* self);
CIMGUI_API ImVector_ImDrawCmd* ImVector_ImDrawCmd_ImVector_ImDrawCmdVector(const ImVector_ImDrawCmd src);
CIMGUI_API bool ImVector_ImDrawCmd_empty(const ImVector_ImDrawCmd* self);

CIMGUI_API ImVector_ImDrawIdx* ImVector_ImDrawIdx_ImVector_ImDrawIdx(void);
CIMGUI_API void ImVector_ImDrawIdx_destroy(ImVector_ImDrawIdx* self);
CIMGUI_API ImVector_ImDrawIdx* ImVector_ImDrawIdx_ImVector_ImDrawIdxVector(const ImVector_ImDrawIdx src);
CIMGUI_API bool ImVector_ImDrawIdx_empty(const ImVector_ImDrawIdx* self);

CIMGUI_API ImVector_ImVec2* ImVector_ImVec2_ImVector_ImVec2(void);
CIMGUI_API void ImVector_ImVec2_destroy(ImVector_ImVec2* self);
CIMGUI_API ImVector_ImVec2* ImVector_ImVec2_ImVector_ImVec2Vector(const ImVector_ImVec2 src);
CIMGUI_API bool ImVector_ImVec2_empty(const ImVector_ImVec2* self);
```
That will group the related function sets together in a much more readable manner.

**Comment by sonoro1234** [comment]
In fact you dont need  cimgui_impl.h at all: LuaJIT-ImGui is not using it but instead it includes several imgui_impl_xxx.h

**Comment by vadtec** [comment]
> In fact you dont need cimgui_impl.h at all: LuaJIT-ImGui is not using it but instead it includes several imgui_impl_xxx.h

I'll give that a try. When I tried it during the previous attempts, I kept getting errors so I used cimgui_impl.h since I knew it would work.

If you believe using the imgui_impl_*.h would be the better route I will go that way.

**Comment by sonoro1234** [comment]
When you set as source file imgui_impl_opengl3.cpp for example it already includes imgui_impl_opengl3.h

**Comment by sonoro1234** [comment]
merged in master

**Comment by vadtec** [comment]
So far everything is working as expected. Will open a new issue if something creeps up. Closing issue.
