### ISSUE TITLE
Generator vs Generator2

### ISSUE THREAD

**Issue by PathogenDavid** [cimgui/cimgui#92]
I'm experimenting with cimgui's generator to generate bindings for the ImGui `docking` beta branch, and it is unclear to me what the differences are between `generator` and `generator2`. The readme states to use `generator`, but [according to this comment](https://github.com/cimgui/cimgui/issues/87#issuecomment-457933336) `generator2` is more robust. Additionally, the generated files in the repo appear to have been generated with `generator2`.

Should the readme be updated? Is there a practical reason to keep `generator` around anymore if it's been superseded?

Thanks!

**Comment by sonoro1234** [comment]
> Should the readme be updated? Is there a practical reason to keep `generator` around anymore if it's been superseded?

Just updated. 
The original generator is keeped in case anyone wants to use it as has done in the past.

**Comment by PathogenDavid** [comment]
Cool, thanks for the clarification!

**Comment by jeffvandyke** [comment]
I just ran into this same confusion - It seems best to rename "generator2.lua" to "generator.lua" and the current "generator.lua" to "generator_old.lua". Would you be open to a PR?

**Comment by sonoro1234** [comment]
Just done.
