### ISSUE TITLE
Redefinition of 'TextRange' on macOS

### ISSUE THREAD

**Issue by prime31** [cimgui/cimgui#96]
It seems that Apple defines a TextRange struct in AE/AERegistry.h (AppleEvents Registry Interface). Renaming the TextRange struct to ImTextRange fixes the issue. If you would like a PR for the change let me know and I'll get one to you.

**Comment by sonoro1234** [comment]
Autogenerated?

**Comment by sonoro1234** [comment]
When compiling which code is AE/AERegistry.h included?

Posible solution (in the code that you try to compile with cimgui.h)
https://stackoverflow.com/questions/2680502/how-to-resolve-two-structures-with-the-same-name

**Comment by prime31** [comment]
I can’t actually figure out how the AERegistry code is included. It seems to somehow be auto-included for App Store builds.

That macro hack is beautiful. I’ll give that a shot and report back this evening.

**Comment by prime31** [comment]
Works like a champ! Thanks for passing on the link. I would have never thought of that one.

**Comment by code-disaster** [comment]
Note for future references: AERegistry is pulled in, six include levels deep, by `Metal.h`.
